/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Stage 14: Comprehensive Orthopedic Clinic Template (India Business Essentials)
 * Dr. Amit Orthopedic Clinic, Mumbai
 */

import { TenantConfig } from '../../types/config.ts';

export const clinicTemplate: TenantConfig = {
  id: 'template-clinic',
  slug: 'dr-amit-ortho',
  name: 'Dr. Amit Orthopedic Clinic',
  businessTypeKey: 'clinic',
  status: 'active',
  schemaVersion: 1,
  profile: {
    phone: '+91 98201 54321',
    email: 'care@dramitclinic.com',
    address: 'Suite 204, MedHealth Complex, Linking Road, Bandra West, Mumbai, Maharashtra 400050',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    currency: 'INR',
    taxRate: 5,
    gstin: '27AABCA1234F1Z8',
    stateCode: '27',
    stateName: 'Maharashtra',
  },
  branding: {
    primary: '#0284c7', // Sky blue
    secondary: '#0f172a',
    accent: '#38bdf8',
    font: 'sans-serif',
    radius: 'md',
    buttonStyle: 'solid',
    mode: 'light',
    loginHeadline: 'Dr. Amit Orthopedic Clinic — Care & Mobility Hub',
  },
  modules: {
    appointments: { enabled: true },
    patients: { enabled: true },
    prescriptions: { enabled: true },
    billing: { enabled: true },
    pharmacy: { enabled: true },
    queue: { enabled: true },
  },
  roleLabels: {
    business_admin: 'Lead Orthopedic Surgeon',
    staff: 'Front Desk Assistant',
  },
  entities: [
    // 1. Patients (12 fields, sensitive fields protected)
    {
      key: 'patients',
      singular: 'Patient',
      plural: 'Patients',
      icon: 'HeartPulse',
      system: true,
      permissionKey: 'records.patients',
      emptyStateText: 'No patients registered yet. Register your first patient to start appointments.',
      searchableFields: ['fullName', 'phone', 'patientId'],
      defaultSort: { field: 'patientId', dir: 'desc' },
      listColumns: ['patientId', 'fullName', 'phone', 'gender', 'bloodGroup', 'emergencyPhone'],
      fields: [
        {
          key: 'patientId',
          label: 'Patient ID',
          type: 'autoId',
          autoIdPattern: 'PAT-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'fullName',
          label: 'Patient Full Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Contact Phone',
          type: 'phone',
          required: true,
          validation: { formatPreset: 'phone' },
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'dob',
          label: 'Date of Birth',
          type: 'date',
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'gender',
          label: 'Gender',
          type: 'select',
          options: [
            { value: 'female', label: 'Female' },
            { value: 'male', label: 'Male' },
            { value: 'other', label: 'Other' },
          ],
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'bloodGroup',
          label: 'Blood Group',
          type: 'select',
          options: [
            { value: 'O+', label: 'O Positive (O+)' },
            { value: 'O-', label: 'O Negative (O-)' },
            { value: 'A+', label: 'A Positive (A+)' },
            { value: 'A-', label: 'A Negative (A-)' },
            { value: 'B+', label: 'B Positive (B+)' },
            { value: 'B-', label: 'B Negative (B-)' },
            { value: 'AB+', label: 'AB Positive (AB+)' },
            { value: 'AB-', label: 'AB Negative (AB-)' },
          ],
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'address',
          label: 'Residential Address',
          type: 'text',
          order: 7,
          showInList: false,
          width: 'full',
        },
        {
          key: 'emergencyContact',
          label: 'Emergency Contact Person',
          type: 'text',
          order: 8,
          showInList: false,
          width: 'half',
        },
        {
          key: 'emergencyPhone',
          label: 'Emergency Phone',
          type: 'phone',
          order: 9,
          showInList: true,
          width: 'half',
        },
        {
          key: 'medicalHistory',
          label: 'Medical History',
          type: 'textarea',
          sensitive: true,
          order: 10,
          showInList: false,
          width: 'full',
          helpText: 'Confidential patient clinical history, prior surgeries, chronic conditions',
        },
        {
          key: 'allergies',
          label: 'Known Drug Allergies',
          type: 'text',
          sensitive: true,
          order: 11,
          showInList: false,
          width: 'half',
          helpText: 'e.g. Penicillin, Sulfa drugs, NSAIDs',
        },
        {
          key: 'medicalNotes',
          label: 'Confidential Doctor Notes',
          type: 'textarea',
          sensitive: true,
          order: 12,
          showInList: false,
          width: 'full',
        },
      ],
    },

    // 2. Appointments (8 fields, workflow enabled)
    {
      key: 'appointments',
      singular: 'Appointment',
      plural: 'Appointments',
      icon: 'Calendar',
      system: true,
      permissionKey: 'records.appointments',
      emptyStateText: 'No consultations scheduled for today.',
      searchableFields: ['patientName', 'doctorName', 'appointmentDate'],
      defaultSort: { field: 'appointmentDate', dir: 'asc' },
      listColumns: ['appointmentId', 'patientName', 'doctorName', 'appointmentDate', 'appointmentTime', 'status'],
      fields: [
        {
          key: 'appointmentId',
          label: 'Appointment Number',
          type: 'autoId',
          autoIdPattern: 'APT-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'patientName',
          label: 'Patient Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'doctorName',
          label: 'Doctor in Charge',
          type: 'text',
          defaultValue: 'Dr. Amit Sharma',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'appointmentDate',
          label: 'Appointment Date',
          type: 'date',
          required: true,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'appointmentTime',
          label: 'Appointment Slot',
          type: 'text',
          defaultValue: '10:30 AM',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'durationMinutes',
          label: 'Duration (Minutes)',
          type: 'number',
          defaultValue: 20,
          order: 6,
          showInList: false,
          width: 'half',
        },
        {
          key: 'type',
          label: 'Visit Reason',
          type: 'select',
          options: [
            { value: 'new', label: 'New Patient Consultation' },
            { value: 'follow_up', label: 'Follow-up Checkup' },
            { value: 'post_op', label: 'Post-operative Review' },
            { value: 'physio', label: 'Physiotherapy Session' },
          ],
          defaultValue: 'new',
          order: 7,
          showInList: true,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Appointment Status',
          type: 'select',
          options: [
            { value: 'scheduled', label: 'Scheduled', color: 'blue' },
            { value: 'arrived', label: 'Arrived / Waiting', color: 'amber' },
            { value: 'in_consultation', label: 'In Consultation', color: 'purple' },
            { value: 'completed', label: 'Completed', color: 'green' },
            { value: 'no_show', label: 'No-show', color: 'slate' },
          ],
          defaultValue: 'scheduled',
          order: 8,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 3. Consultations (6 fields)
    {
      key: 'consultations',
      singular: 'Consultation Note',
      plural: 'Consultation Notes',
      icon: 'Stethoscope',
      system: true,
      permissionKey: 'records.consultations',
      emptyStateText: 'No clinical notes recorded yet.',
      searchableFields: ['patientName', 'chiefComplaint', 'diagnosis'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['consultationId', 'patientName', 'chiefComplaint', 'diagnosis', 'followUpDate'],
      fields: [
        {
          key: 'consultationId',
          label: 'Consultation ID',
          type: 'autoId',
          autoIdPattern: 'CNS-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'patientName',
          label: 'Patient Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'chiefComplaint',
          label: 'Chief Complaint',
          type: 'text',
          required: true,
          order: 3,
          showInList: true,
          width: 'full',
          helpText: 'e.g. Right knee pain following athletic twist 3 days ago',
        },
        {
          key: 'diagnosis',
          label: 'Clinical Diagnosis',
          type: 'text',
          required: true,
          order: 4,
          showInList: true,
          width: 'full',
          helpText: 'e.g. Grade II Medial Meniscus Tear, Right Knee',
        },
        {
          key: 'treatmentPlan',
          label: 'Treatment Plan & Exercises',
          type: 'textarea',
          order: 5,
          showInList: false,
          width: 'full',
        },
        {
          key: 'followUpDate',
          label: 'Recommended Follow-up',
          type: 'date',
          order: 6,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 4. Prescriptions (6 fields, printable & WhatsApp shareable)
    {
      key: 'prescriptions',
      singular: 'Prescription',
      plural: 'Prescriptions',
      icon: 'FileText',
      system: true,
      permissionKey: 'records.prescriptions',
      emptyStateText: 'No prescriptions issued yet.',
      searchableFields: ['patientName', 'medicineName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['prescriptionId', 'patientName', 'medicineName', 'dosage', 'frequency', 'duration'],
      fields: [
        {
          key: 'prescriptionId',
          label: 'Prescription Code',
          type: 'autoId',
          autoIdPattern: 'RX-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'patientName',
          label: 'Patient Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'medicineName',
          label: 'Medicine & Strength',
          type: 'text',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
          helpText: 'e.g. Tab Aceclofenac 100mg + Paracetamol 325mg',
        },
        {
          key: 'dosage',
          label: 'Dosage / Quantity',
          type: 'text',
          defaultValue: '1 tablet',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'frequency',
          label: 'Intake Schedule',
          type: 'select',
          options: [
            { value: 'once_daily', label: 'Once daily (after breakfast)' },
            { value: 'twice_daily', label: 'Twice daily (after meals)' },
            { value: 'thrice_daily', label: 'Thrice daily (after meals)' },
            { value: 'sos', label: 'When needed for severe pain (SOS)' },
          ],
          defaultValue: 'twice_daily',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'duration',
          label: 'Course Duration',
          type: 'text',
          defaultValue: '5 days',
          order: 6,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 5. Pharmacy Stock (Batch & Expiry Tracked, 10 fields)
    {
      key: 'pharmacy_stock',
      singular: 'Medicine & Stock Item',
      plural: 'Pharmacy Stock',
      icon: 'Pill',
      system: true,
      batchTracked: true,
      permissionKey: 'records.pharmacy',
      emptyStateText: 'Pharmacy catalog is currently empty.',
      searchableFields: ['itemName', 'batchNumber', 'taxCode'],
      defaultSort: { field: 'expiryDate', dir: 'asc' },
      listColumns: ['itemName', 'batchNumber', 'expiryDate', 'stockQuantity', 'sellingPriceMinor', 'taxCode'],
      fields: [
        {
          key: 'itemName',
          label: 'Medicine / Item Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'batchNumber',
          label: 'Batch Number',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
          helpText: 'Printed on foil/box, e.g. BT-2026-08A',
        },
        {
          key: 'expiryDate',
          label: 'Expiry Date',
          type: 'date',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
          helpText: 'Perishable expiration date for patient safety',
        },
        {
          key: 'stockQuantity',
          label: 'Current Quantity',
          type: 'number',
          defaultValue: 100,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'reorderLevel',
          label: 'Reorder Level',
          type: 'number',
          defaultValue: 25,
          order: 5,
          showInList: false,
          width: 'half',
          helpText: 'Sends warning when stock drops below this number',
        },
        {
          key: 'unit',
          label: 'Unit of Measure',
          type: 'select',
          options: [
            { value: 'strip_10', label: 'Strip (10 Tablets)' },
            { value: 'strip_15', label: 'Strip (15 Tablets)' },
            { value: 'bottle', label: 'Bottle / Syrup' },
            { value: 'tube', label: 'Ointment Tube' },
            { value: 'splint', label: 'Piece (Brace / Splint)' },
          ],
          defaultValue: 'strip_10',
          order: 6,
          showInList: false,
          width: 'half',
        },
        {
          key: 'purchasePriceMinor',
          label: 'Purchase Rate (Cost)',
          type: 'currency',
          defaultValue: 6000,
          order: 7,
          showInList: false,
          width: 'half',
        },
        {
          key: 'sellingPriceMinor',
          label: 'Selling Price (MRP)',
          type: 'currency',
          defaultValue: 9500,
          order: 8,
          showInList: true,
          width: 'half',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '300490',
          hsnOrSac: '300490',
          taxRate: 12,
          order: 9,
          showInList: true,
          width: 'half',
          helpText: 'Tax code: 300490 (Allopathic pharmaceuticals, 12% GST)',
        },
        {
          key: 'supplierName',
          label: 'Medicine Supplier',
          type: 'text',
          defaultValue: 'Apex MedPharma Distributors',
          order: 10,
          showInList: false,
          width: 'half',
        },
      ],
    },

    // 6. Suppliers (5 fields)
    {
      key: 'suppliers',
      singular: 'Supplier',
      plural: 'Suppliers',
      icon: 'Truck',
      system: true,
      permissionKey: 'records.suppliers',
      emptyStateText: 'No medical distributors registered.',
      searchableFields: ['name', 'phone'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['supplierId', 'name', 'phone', 'email', 'itemsSupplied'],
      fields: [
        {
          key: 'supplierId',
          label: 'Supplier Code',
          type: 'autoId',
          autoIdPattern: 'SUP-{SEQ:3}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'name',
          label: 'Distributor / Agency Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Contact Phone',
          type: 'phone',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'email',
          label: 'Email Address',
          type: 'email',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'itemsSupplied',
          label: 'Supplied Categories',
          type: 'text',
          defaultValue: 'Analgesics, Anti-inflammatories, Splints, Knee Braces',
          order: 5,
          showInList: true,
          width: 'full',
        },
      ],
    },

    // 7. Invoices (India GST Compliant, 8 fields)
    {
      key: 'invoices',
      singular: 'Invoice',
      plural: 'Invoices',
      icon: 'Receipt',
      system: true,
      permissionKey: 'records.invoices',
      emptyStateText: 'No invoices billed yet.',
      searchableFields: ['invoiceId', 'patientName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['invoiceId', 'patientName', 'consultationFeeMinor', 'grandTotalMinor', 'paymentStatus', 'paymentMethod'],
      fields: [
        {
          key: 'invoiceId',
          label: 'Invoice Number',
          type: 'autoId',
          autoIdPattern: 'INV-2026-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'patientName',
          label: 'Patient Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'consultationFeeMinor',
          label: 'Consultation Fee',
          type: 'currency',
          defaultValue: 80000, // ₹800
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'medicineChargesMinor',
          label: 'Pharmacy / Medicine Total',
          type: 'currency',
          defaultValue: 45000, // ₹450
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '999312',
          hsnOrSac: '999312',
          order: 5,
          showInList: false,
          width: 'half',
        },
        {
          key: 'isInterState',
          label: 'Inter-State Supply (100% IGST)',
          type: 'checkbox',
          defaultValue: false,
          order: 6,
          showInList: false,
          width: 'half',
          helpText: 'Unchecked = Intra-state Mumbai/Maharashtra (CGST 50% + SGST 50%)',
        },
        {
          key: 'paymentStatus',
          label: 'Payment Status',
          type: 'select',
          options: [
            { value: 'paid', label: 'Paid in Full', color: 'green' },
            { value: 'pending', label: 'Pending Payment', color: 'amber' },
            { value: 'overdue', label: 'Overdue (7+ Days)', color: 'rose' },
          ],
          defaultValue: 'paid',
          order: 7,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentMethod',
          label: 'Payment Mode',
          type: 'select',
          options: [
            { value: 'upi', label: 'UPI / QR Code' },
            { value: 'cash', label: 'Cash at Counter' },
            { value: 'card', label: 'Debit / Credit Card' },
          ],
          defaultValue: 'upi',
          order: 8,
          showInList: true,
          width: 'half',
        },
        {
          key: 'grandTotalMinor',
          label: 'Final Amount (Incl. GST)',
          type: 'currency',
          defaultValue: 125000, // ₹1,250
          order: 9,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 8. Walk-in Queue (Token Management, 6 fields)
    {
      key: 'walkin_queue',
      singular: 'Queue Token',
      plural: 'Walk-in Queue',
      icon: 'Users',
      system: true,
      permissionKey: 'records.queue',
      emptyStateText: 'No patients in waiting lounge right now.',
      searchableFields: ['tokenId', 'patientName'],
      defaultSort: { field: 'tokenId', dir: 'asc' },
      listColumns: ['tokenId', 'patientName', 'purpose', 'status', 'arrivalTime'],
      fields: [
        {
          key: 'tokenId',
          label: 'Token Number',
          type: 'autoId',
          autoIdPattern: 'A-{SEQ:2}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'patientName',
          label: 'Patient Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Mobile Phone',
          type: 'phone',
          order: 3,
          showInList: false,
          width: 'half',
        },
        {
          key: 'purpose',
          label: 'Visit Reason',
          type: 'text',
          defaultValue: 'Knee Pain Consultation',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Queue Status',
          type: 'select',
          options: [
            { value: 'waiting', label: 'Waiting in Lounge', color: 'amber' },
            { value: 'with_doctor', label: 'With Doctor (Room 1)', color: 'blue' },
            { value: 'done', label: 'Consultation Finished', color: 'green' },
          ],
          defaultValue: 'waiting',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'arrivalTime',
          label: 'Arrival Time',
          type: 'text',
          defaultValue: '10:15 AM',
          order: 6,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 9. Staff & Doctors (4 fields)
    {
      key: 'staff_doctors',
      singular: 'Clinic Staff & Doctor',
      plural: 'Doctors & Staff',
      icon: 'UserCheck',
      system: true,
      permissionKey: 'records.staff',
      emptyStateText: 'No staff profiles recorded.',
      searchableFields: ['name', 'specialization'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['doctorId', 'name', 'specialization', 'workingHours', 'phone'],
      fields: [
        {
          key: 'doctorId',
          label: 'Staff ID',
          type: 'autoId',
          autoIdPattern: 'DOC-{SEQ:2}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'name',
          label: 'Full Name & Qualifications',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'specialization',
          label: 'Specialty / Role',
          type: 'text',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'workingHours',
          label: 'OPD Consulting Hours',
          type: 'text',
          defaultValue: '10:00 AM - 02:00 PM, 05:00 PM - 08:30 PM',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Direct Phone',
          type: 'phone',
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },
  ],

  // 2 Workflow Boards
  workflows: [
    {
      id: 'clinic_appointments_workflow',
      title: 'Consultation Workflow Board',
      entityKey: 'appointments',
      statusFieldKey: 'status',
      stages: [
        { key: 'scheduled', label: 'Scheduled', color: 'bg-blue-50 border-blue-200 text-blue-800' },
        { key: 'arrived', label: 'Arrived / Waiting', color: 'bg-amber-50 border-amber-200 text-amber-800' },
        { key: 'in_consultation', label: 'In Consultation', color: 'bg-purple-50 border-purple-200 text-purple-800' },
        { key: 'completed', label: 'Completed', color: 'bg-emerald-50 border-emerald-200 text-emerald-800' },
        { key: 'no_show', label: 'No-Show', color: 'bg-slate-50 border-slate-200 text-slate-700' },
      ],
      cardDisplayFields: ['patientName', 'appointmentTime', 'type'],
    },
    {
      id: 'clinic_queue_workflow',
      title: 'Live Walk-in Token Board',
      entityKey: 'walkin_queue',
      statusFieldKey: 'status',
      stages: [
        { key: 'waiting', label: 'Waiting', color: 'bg-amber-50 border-amber-200 text-amber-800' },
        { key: 'with_doctor', label: 'With Doctor (Room 1)', color: 'bg-sky-50 border-sky-200 text-sky-800' },
        { key: 'done', label: 'Finished', color: 'bg-emerald-50 border-emerald-200 text-emerald-800' },
      ],
      cardDisplayFields: ['tokenId', 'patientName', 'purpose', 'arrivalTime'],
    },
  ],

  // 4 Automation Presets
  automations: [
    {
      id: 'auto_clinic_reminder',
      name: 'Appointment Reminder (24h Before)',
      description: 'Sends automated WhatsApp & SMS reminder to patient one day before their scheduled visit.',
      trigger: 'scheduled_daily',
      entityKey: 'appointments',
      condition: { field: 'status', operator: 'eq', value: 'scheduled' },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'appointment_reminder',
      },
      enabled: true,
    },
    {
      id: 'auto_clinic_low_stock',
      name: 'Low-Stock Medicine Alert',
      description: 'Dispatches alert notification to lead surgeon and clinic assistant when medicine inventory drops below reorder point.',
      trigger: 'low_stock',
      entityKey: 'pharmacy_stock',
      condition: { field: 'stockQuantity', operator: 'lte', value: 25 },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'low_stock_alert',
      },
      enabled: true,
    },
    {
      id: 'auto_clinic_prescription_ready',
      name: 'Prescription Ready Notification',
      description: 'Sends prescription notice to patient via WhatsApp when clinical medication is recorded.',
      trigger: 'record_create',
      entityKey: 'prescriptions',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'prescription_ready',
      },
      enabled: true,
    },
    {
      id: 'auto_clinic_invoice_overdue',
      name: 'Invoice Payment Due Reminder',
      description: 'Sends polite payment reminder for pending bills older than 7 days.',
      trigger: 'status_change',
      entityKey: 'invoices',
      condition: { field: 'paymentStatus', operator: 'eq', value: 'overdue' },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'invoice_due',
      },
      enabled: true,
    },
  ],

  // 6 Dashboard Widgets
  dashboard: {
    widgets: [
      {
        id: 'widget-today-appointments',
        type: 'metric',
        title: "Today's Consultations",
        span: 1,
        order: 1,
        dataSource: { entity: 'appointments', aggregate: 'count', range: 'today' },
      },
      {
        id: 'widget-queue-length',
        type: 'metric',
        title: 'Walk-in Queue',
        span: 1,
        order: 2,
        dataSource: { entity: 'walkin_queue', aggregate: 'count', filter: { field: 'status', operator: 'eq', value: 'waiting' } },
      },
      {
        id: 'widget-total-patients',
        type: 'metric',
        title: 'Registered Patients',
        span: 1,
        order: 3,
        dataSource: { entity: 'patients', aggregate: 'count' },
      },
      {
        id: 'widget-revenue-30d',
        type: 'metric',
        title: 'Clinic Revenue (30d)',
        span: 1,
        order: 4,
        dataSource: { entity: 'invoices', aggregate: 'sum', field: 'grandTotalMinor', range: '30d' },
      },
      {
        id: 'widget-low-stock-count',
        type: 'metric',
        title: 'Low-Stock Perishables',
        span: 1,
        order: 5,
        dataSource: { entity: 'pharmacy_stock', aggregate: 'count', filter: { field: 'stockQuantity', operator: 'lt', value: 30 } },
      },
      {
        id: 'widget-pending-payments',
        type: 'metric',
        title: 'Pending Billed Receivables',
        span: 1,
        order: 6,
        dataSource: { entity: 'invoices', aggregate: 'count', filter: { field: 'paymentStatus', operator: 'neq', value: 'paid' } },
      },
    ],
  },

  // 4 Reports
  reports: [
    {
      id: 'rep_clinic_daily_patients',
      title: 'Daily Patient Consultation Volume',
      description: 'Breakdown of new consultations vs follow-ups and completed sessions.',
      category: 'operations',
      entityKey: 'appointments',
      metricKey: 'count',
      timeframeDefault: 'today',
    },
    {
      id: 'rep_clinic_revenue',
      title: 'Clinic Revenue & GST Summary',
      description: 'Consultation receipts, pharmacy billings, and GST tax breakup.',
      category: 'tax',
      entityKey: 'invoices',
      metricKey: 'grandTotalMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_clinic_noshow',
      title: 'No-Show & Cancellation Analysis',
      description: 'Track patient attendance patterns to optimize OPD schedule slots.',
      category: 'operations',
      entityKey: 'appointments',
      metricKey: 'status',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_clinic_stock_valuation',
      title: 'Pharmacy Stock Valuation & Expiry Audit',
      description: 'Total holding inventory valuation and batches expiring within 60 days.',
      category: 'inventory',
      entityKey: 'pharmacy_stock',
      metricKey: 'stockQuantity',
      timeframeDefault: '30d',
    },
  ],

  website: {
    draft: {
      headline: 'Restoring Natural Mobility & Active Life',
      tagline: 'Comprehensive Orthopedic, Joint Care & Sports Injury Clinic led by Dr. Amit Sharma.',
      themeName: 'clean-clinical',
      sections: [
        {
          id: 'sec-hero',
          type: 'hero',
          title: 'Specialized Orthopedic Care in Mumbai',
          subtitle: 'Over 15 years of surgical excellence in joint reconstruction, knee arthroscopy, and spine rehabilitation.',
          enabled: true,
          content: { ctaText: 'Book OPD Consultation', ctaLink: '#booking' },
        },
        {
          id: 'sec-services',
          type: 'services',
          title: 'Clinical Specialties',
          enabled: true,
          content: {
            items: [
              { name: 'Knee & Hip Arthroscopy', desc: 'Minimally invasive joint repair for rapid recovery and lasting relief.' },
              { name: 'Sports Injury Rehabilitation', desc: 'Targeted recovery regimens for ligament tears and muscular sprains.' },
              { name: 'Fracture & Trauma Management', desc: 'Advanced casting, splinting, and immediate orthopedic emergency care.' },
            ],
          },
        },
      ],
    },
    published: null,
  },
  subscription: {
    plan: 'professional',
    status: 'active',
    startedAt: '2026-01-01T00:00:00Z',
    renewsAt: '2027-01-01T00:00:00Z',
    limits: { users: 10, records: 50000, storageMb: 5000, modules: ['appointments', 'patients', 'prescriptions', 'billing'] },
    usage: { users: 2, records: 48, storageMb: 12 },
  },
};
