/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Stage 14: Comprehensive Gym / Fitness Studio Template (India Business Essentials)
 * Pulse Fitness & Strength Studio, Koregaon Park, Pune
 */

import { TenantConfig } from '../../types/config.ts';

export const gymTemplate: TenantConfig = {
  id: 'template-gym',
  slug: 'pulse-fitness-pune',
  name: 'Pulse Fitness & Strength Studio',
  businessTypeKey: 'gym',
  status: 'active',
  schemaVersion: 1,
  profile: {
    phone: '+91 97654 32109',
    email: 'train@pulsefitness.in',
    address: 'Level 3, North Main Road, Koregaon Park, Pune, Maharashtra 411001',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    currency: 'INR',
    taxRate: 18,
    gstin: '27AABCP1122D1Z6',
    stateCode: '27',
    stateName: 'Maharashtra',
  },
  branding: {
    primary: '#16a34a', // Emerald green
    secondary: '#0f172a',
    accent: '#22c55e',
    font: 'sans-serif',
    radius: 'lg',
    buttonStyle: 'solid',
    mode: 'light',
    loginHeadline: 'Pulse Fitness & Strength Studio — Member Management',
  },
  modules: {
    members: { enabled: true },
    classes: { enabled: true },
    training: { enabled: true },
    billing: { enabled: true },
    checkin: { enabled: true },
  },
  roleLabels: {
    business_admin: 'Head Fitness Coach / Studio Manager',
    staff: 'Strength Trainer & Front Desk',
  },
  entities: [
    // 1. Members (7 fields)
    {
      key: 'members',
      singular: 'Gym Member',
      plural: 'Members',
      icon: 'UserCheck',
      system: true,
      permissionKey: 'records.members',
      emptyStateText: 'No members enrolled yet.',
      searchableFields: ['fullName', 'phone', 'memberId'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['memberId', 'fullName', 'phone', 'planName', 'status', 'expiryDate'],
      fields: [
        {
          key: 'memberId',
          label: 'Member ID',
          type: 'autoId',
          autoIdPattern: 'MEM-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'fullName',
          label: 'Member Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Mobile Phone',
          type: 'phone',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'planName',
          label: 'Membership / Package',
          type: 'text',
          defaultValue: 'Quarterly Strength & Conditioning',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'joinDate',
          label: 'Joined Date',
          type: 'date',
          defaultValue: '2026-06-01',
          order: 5,
          showInList: false,
          width: 'half',
        },
        {
          key: 'expiryDate',
          label: 'Plan Expiry Date',
          type: 'date',
          required: true,
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Access Status',
          type: 'select',
          options: [
            { value: 'active', label: 'Active Member', color: 'green' },
            { value: 'expiring_soon', label: 'Expiring Soon (<7d)', color: 'amber' },
            { value: 'expired', label: 'Expired / Lapsed', color: 'rose' },
          ],
          defaultValue: 'active',
          order: 7,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 2. Membership Plans (Recurring, 5 fields)
    {
      key: 'membership_plans',
      singular: 'Membership Plan',
      plural: 'Membership Plans',
      icon: 'Award',
      system: true,
      permissionKey: 'records.plans',
      emptyStateText: 'No membership tiers created.',
      searchableFields: ['planName'],
      defaultSort: { field: 'priceMinor', dir: 'asc' },
      listColumns: ['planName', 'validityMonths', 'priceMinor', 'sessions', 'autoRenew'],
      fields: [
        {
          key: 'planName',
          label: 'Membership / Package',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'validityMonths',
          label: 'Validity (Months)',
          type: 'number',
          defaultValue: 3,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'priceMinor',
          label: 'Plan Fee',
          type: 'currency',
          defaultValue: 1200000, // ₹12,000
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'sessions',
          label: 'Group Classes Included',
          type: 'number',
          defaultValue: 24,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'autoRenew',
          label: 'Auto-Renew on Expiry',
          type: 'checkbox',
          defaultValue: true,
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 3. Classes (Capacity specified, 5 fields)
    {
      key: 'classes',
      singular: 'Studio Class',
      plural: 'Classes & Sessions',
      icon: 'Flame',
      system: true,
      permissionKey: 'records.classes',
      emptyStateText: 'No studio group classes scheduled.',
      searchableFields: ['title', 'instructor'],
      defaultSort: { field: 'scheduleTime', dir: 'asc' },
      listColumns: ['title', 'instructor', 'capacity', 'scheduleTime', 'room'],
      fields: [
        {
          key: 'title',
          label: 'Class Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'capacity',
          label: 'How many people can join this class?',
          type: 'number',
          defaultValue: 15,
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
          helpText: 'Maximum participants allowed for safety and equipment availability',
        },
        {
          key: 'instructor',
          label: 'Lead Instructor',
          type: 'text',
          defaultValue: 'Coach Rohan',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'scheduleTime',
          label: 'Daily Schedule Slot',
          type: 'text',
          defaultValue: '07:00 AM - 08:00 AM',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'room',
          label: 'Studio Floor',
          type: 'text',
          defaultValue: 'Studio 1 (HIIT & Turf)',
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 4. Class Bookings (Workflow enabled, 4 fields)
    {
      key: 'class_bookings',
      singular: 'Class Booking',
      plural: 'Class Bookings',
      icon: 'CalendarCheck',
      system: true,
      permissionKey: 'records.bookings',
      emptyStateText: 'No class bookings logged.',
      searchableFields: ['memberName', 'className'],
      defaultSort: { field: 'bookingDate', dir: 'asc' },
      listColumns: ['memberName', 'className', 'bookingDate', 'status'],
      fields: [
        {
          key: 'memberName',
          label: 'Member Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'className',
          label: 'Class Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'bookingDate',
          label: 'Date of Session',
          type: 'date',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Attendance Status',
          type: 'select',
          options: [
            { value: 'confirmed', label: 'Confirmed Spot', color: 'blue' },
            { value: 'attended', label: 'Attended Class', color: 'green' },
            { value: 'no_show', label: 'No-Show / Cancelled', color: 'slate' },
          ],
          defaultValue: 'confirmed',
          order: 4,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 5. PT Sessions (1:1 Personal Training, 5 fields)
    {
      key: 'pt_sessions',
      singular: 'PT Session',
      plural: 'Personal Training',
      icon: 'Target',
      system: true,
      permissionKey: 'records.pt',
      emptyStateText: 'No 1-on-1 personal coaching slots scheduled.',
      searchableFields: ['memberName', 'trainerName'],
      defaultSort: { field: 'sessionDate', dir: 'asc' },
      listColumns: ['memberName', 'trainerName', 'sessionDate', 'sessionTime', 'focusArea'],
      fields: [
        {
          key: 'memberName',
          label: 'Member Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'trainerName',
          label: 'Assigned Trainer',
          type: 'text',
          defaultValue: 'Vikram Rajput',
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'sessionDate',
          label: 'Date',
          type: 'date',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'sessionTime',
          label: 'Time Slot',
          type: 'text',
          defaultValue: '06:00 PM',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'focusArea',
          label: 'Workout Focus',
          type: 'text',
          defaultValue: 'Hypertrophy & Lower Body Form',
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 6. Products (Supplements / Merch, 5 fields)
    {
      key: 'products',
      singular: 'Supplement & Gear',
      plural: 'Supplements & Products',
      icon: 'Package',
      system: true,
      permissionKey: 'records.products',
      emptyStateText: 'No supplements or merchandise added.',
      searchableFields: ['name', 'barcode'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['name', 'barcode', 'sellingPriceMinor', 'stock', 'taxCode'],
      fields: [
        {
          key: 'name',
          label: 'Product Title',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'barcode',
          label: 'Barcode / SKU',
          type: 'barcode',
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'sellingPriceMinor',
          label: 'Retail Price (MRP)',
          type: 'currency',
          defaultValue: 320000, // ₹3,200
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'stock',
          label: 'Quantity in Studio',
          type: 'number',
          defaultValue: 20,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '210690',
          hsnOrSac: '210690',
          order: 5,
          showInList: true,
          width: 'half',
          helpText: 'Tax code: 210690 (Whey protein and dietary supplements, 18% GST)',
        },
      ],
    },

    // 7. Invoices (GST Compliant, 6 fields)
    {
      key: 'invoices',
      singular: 'Gym Invoice',
      plural: 'Gym Invoices',
      icon: 'Receipt',
      system: true,
      permissionKey: 'records.invoices',
      emptyStateText: 'No membership invoices billed.',
      searchableFields: ['invoiceId', 'memberName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['invoiceId', 'memberName', 'grandTotalMinor', 'paymentStatus', 'paymentMethod'],
      fields: [
        {
          key: 'invoiceId',
          label: 'Invoice Code',
          type: 'autoId',
          autoIdPattern: 'GYM-2026-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'memberName',
          label: 'Member Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '999291',
          hsnOrSac: '999291',
          order: 3,
          showInList: false,
          width: 'half',
          helpText: 'Tax code: 999291 (Gym and fitness club services, 18% GST)',
        },
        {
          key: 'grandTotalMinor',
          label: 'Total Fee (Incl. 18% GST)',
          type: 'currency',
          defaultValue: 1416000, // ₹14,160 (₹12,000 + 18% GST)
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentStatus',
          label: 'Payment Status',
          type: 'select',
          options: [
            { value: 'paid', label: 'Paid in Full', color: 'green' },
            { value: 'pending', label: 'Pending Renewal', color: 'amber' },
          ],
          defaultValue: 'paid',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentMethod',
          label: 'Payment Mode',
          type: 'select',
          options: [
            { value: 'upi', label: 'UPI / QR Code' },
            { value: 'card', label: 'Debit / Credit Card' },
            { value: 'bank_transfer', label: 'Net Banking' },
          ],
          defaultValue: 'upi',
          order: 6,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 8. Attendance / Check-in (3 fields)
    {
      key: 'attendance',
      singular: 'Member Check-in',
      plural: 'Attendance Log',
      icon: 'CheckCircle',
      system: true,
      permissionKey: 'records.attendance',
      emptyStateText: 'No member turnstile check-ins today.',
      searchableFields: ['memberName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['memberName', 'checkinTime', 'method'],
      fields: [
        {
          key: 'memberName',
          label: 'Member Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'checkinTime',
          label: 'Turnstile Tap Time',
          type: 'text',
          defaultValue: '07:15 AM',
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'method',
          label: 'Check-in Method',
          type: 'select',
          options: [
            { value: 'qr_scanner', label: 'Member App QR Tap' },
            { value: 'nfc_band', label: 'RFID Wristband' },
            { value: 'front_desk', label: 'Manual Front Desk' },
          ],
          defaultValue: 'qr_scanner',
          order: 3,
          showInList: true,
          width: 'half',
        },
      ],
    },
  ],

  // 1 Workflow Board
  workflows: [
    {
      id: 'gym_classes_workflow',
      title: 'Studio Class Attendance Board',
      entityKey: 'class_bookings',
      statusFieldKey: 'status',
      stages: [
        { key: 'confirmed', label: 'Booked Spot', color: 'bg-blue-50 border-blue-200 text-blue-800' },
        { key: 'attended', label: 'Attended & Checked In', color: 'bg-emerald-50 border-emerald-200 text-emerald-800' },
        { key: 'no_show', label: 'Cancelled / No-Show', color: 'bg-slate-50 border-slate-200 text-slate-700' },
      ],
      cardDisplayFields: ['memberName', 'className', 'bookingDate'],
    },
  ],

  // 4 Automations
  automations: [
    {
      id: 'auto_gym_membership_expiring',
      name: 'Membership Expiry Reminder (7d Before)',
      description: 'Dispatches WhatsApp reminder when gym membership plan is expiring in 7 days.',
      trigger: 'scheduled_daily',
      entityKey: 'members',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'membership_expiring',
      },
      enabled: true,
    },
    {
      id: 'auto_gym_class_reminder',
      name: 'Group Class Daily Reminder',
      description: 'Sends WhatsApp alert 2 hours before scheduled studio workout.',
      trigger: 'scheduled_daily',
      entityKey: 'class_bookings',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'appointment_reminder',
      },
      enabled: true,
    },
    {
      id: 'auto_gym_low_stock',
      name: 'Protein Supplement Low-Stock Alert',
      description: 'Sends SMS to gym manager when whey protein inventory drops below 5 tubs.',
      trigger: 'low_stock',
      entityKey: 'products',
      condition: { field: 'stock', operator: 'lte', value: 5 },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'low_stock_alert',
      },
      enabled: true,
    },
    {
      id: 'auto_gym_reengage',
      name: 'Re-engagement Reminder (14 Days Inactive)',
      description: 'Sends encouraging WhatsApp message if member has not checked in for 14 days.',
      trigger: 'scheduled_daily',
      entityKey: 'members',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'membership_expiring',
      },
      enabled: true,
    },
  ],

  // 5 Dashboard Widgets
  dashboard: {
    widgets: [
      {
        id: 'widget-active-members',
        type: 'metric',
        title: 'Active Gym Members',
        span: 1,
        order: 1,
        dataSource: { entity: 'members', aggregate: 'count', filter: { field: 'status', operator: 'eq', value: 'active' } },
      },
      {
        id: 'widget-today-classes',
        type: 'metric',
        title: "Today's Studio Classes",
        span: 1,
        order: 2,
        dataSource: { entity: 'classes', aggregate: 'count' },
      },
      {
        id: 'widget-revenue-30d',
        type: 'metric',
        title: 'Studio Billings (30d)',
        span: 1,
        order: 3,
        dataSource: { entity: 'invoices', aggregate: 'sum', field: 'grandTotalMinor', range: '30d' },
      },
      {
        id: 'widget-expiring-memberships',
        type: 'metric',
        title: 'Expiring This Week',
        span: 1,
        order: 4,
        dataSource: { entity: 'members', aggregate: 'count', filter: { field: 'status', operator: 'eq', value: 'expiring_soon' } },
      },
      {
        id: 'widget-today-attendance',
        type: 'metric',
        title: "Today's Check-ins",
        span: 1,
        order: 5,
        dataSource: { entity: 'attendance', aggregate: 'count' },
      },
    ],
  },

  // 4 Reports
  reports: [
    {
      id: 'rep_gym_renewal_rate',
      title: 'Member Renewal & Retention Rate',
      description: 'Ratio of renewing members vs lapsed accounts across monthly and quarterly plans.',
      category: 'operations',
      entityKey: 'members',
      metricKey: 'status',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_gym_class_attendance',
      title: 'Class Capacity Utilization',
      description: 'Attendance rates and popular slots for HIIT, Yoga, and Strength training.',
      category: 'operations',
      entityKey: 'class_bookings',
      metricKey: 'status',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_gym_revenue_period',
      title: 'Membership Billings & GST Summary',
      description: 'Membership fee receipts, supplement sales, and GST collected.',
      category: 'tax',
      entityKey: 'invoices',
      metricKey: 'grandTotalMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_gym_at_risk_members',
      title: 'At-Risk Member Inactivity Report',
      description: 'List of members who have not visited the gym in 14+ days.',
      category: 'operations',
      entityKey: 'members',
      metricKey: 'expiryDate',
      timeframeDefault: '30d',
    },
  ],

  website: {
    draft: {
      headline: 'Unleash Your Pure Athletic Potential',
      tagline: 'High-performance strength, conditioning, and functional studio training in Koregaon Park, Pune.',
      themeName: 'high-energy',
      sections: [
        {
          id: 'sec-hero',
          type: 'hero',
          title: 'Train with Intention. Live with Power.',
          subtitle: 'Elite Olympic lifting platforms, turf agility tracks, and science-backed conditioning coached by certified athletes.',
          enabled: true,
          content: { ctaText: 'Claim 3-Day Studio Pass', ctaLink: '#booking' },
        },
        {
          id: 'sec-services',
          type: 'services',
          title: 'Studio Training Programs',
          enabled: true,
          content: {
            items: [
              { name: 'Strength & Hypertrophy', desc: 'Progressive overload training with premium calibrated iron and Eleiko barbells.' },
              { name: 'HIIT & Functional Conditioning', desc: 'High-intensity interval circuits to boost VO2 max and metabolic endurance.' },
              { name: '1-on-1 Athletic Coaching', desc: 'Personalized biomechanics analysis, nutrition protocols, and dedicated mentoring.' },
            ],
          },
        },
      ],
    },
    published: null,
  },
  subscription: {
    plan: 'professional',
    status: 'active',
    startedAt: '2026-01-01T00:00:00Z',
    renewsAt: '2027-01-01T00:00:00Z',
    limits: { users: 10, records: 50000, storageMb: 5000, modules: ['members', 'classes', 'training', 'billing'] },
    usage: { users: 2, records: 40, storageMb: 10 },
  },
};
