/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Stage 15: Comprehensive Hotel / Guesthouse Template (India Business Essentials)
 * The Grand Heritage Haveli & Guesthouse, Amber Fort Enclave, Jaipur, Rajasthan
 */

import { TenantConfig } from '../../types/config.ts';
import { universalCoreEntities } from '../universalCore.ts';

export const hotelTemplate: TenantConfig = {
  id: 'template-hotel',
  slug: 'heritage-haveli-jaipur',
  name: 'The Grand Heritage Haveli & Guesthouse',
  businessTypeKey: 'hotel',
  status: 'active',
  schemaVersion: 1,
  profile: {
    phone: '+91 98290 12345',
    email: 'stay@heritagehaveli.in',
    address: 'Heritage Palace Road, Amber Fort Enclave, Jaipur, Rajasthan 302028',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    currency: 'INR',
    taxRate: 12, // Standard Indian GST on hotel rooms under ₹7,500/night
    gstin: '08AAACH1234F1Z8',
    stateCode: '08',
    stateName: 'Rajasthan',
  },
  branding: {
    primary: '#b45309', // Heritage Amber Gold
    secondary: '#1e1b4b', // Deep Royal Indigo
    accent: '#d97706',
    font: 'serif',
    radius: 'lg',
    buttonStyle: 'solid',
    mode: 'light',
    loginHeadline: 'The Grand Heritage Haveli — Front Desk & Property Operations',
  },
  modules: {
    rooms: { enabled: true },
    reservations: { enabled: true },
    guests: { enabled: true },
    folios: { enabled: true },
    billing: { enabled: true },
    housekeeping: { enabled: true },
    room_service: { enabled: true },
  },
  roleLabels: {
    business_admin: 'Guesthouse General Manager',
    staff: 'Front Desk Executive & Concierge',
  },
  entities: [
    // 1. Rooms — Bookable Resource primitive
    {
      key: 'rooms',
      singular: 'Room',
      plural: 'Rooms',
      icon: 'Bed',
      system: true,
      isBookable: true,
      permissionKey: 'records.rooms',
      emptyStateText: 'No rooms configured yet. Add your guesthouse rooms or suites.',
      listColumns: ['roomNumber', 'roomType', 'baseRateMinor', 'maxOccupancy', 'status', 'floor'],
      defaultSort: { field: 'roomNumber', dir: 'asc' },
      searchableFields: ['roomNumber', 'roomType', 'status', 'floor'],
      fields: [
        {
          key: 'roomNumber',
          label: 'Room Number',
          type: 'text',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'roomType',
          label: 'Room Category',
          type: 'select',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
          options: [
            { value: 'standard', label: 'Standard Heritage Room' },
            { value: 'deluxe', label: 'Deluxe Courtyard View' },
            { value: 'suite', label: 'Royal Haveli Suite' },
            { value: 'maharaja', label: 'Maharaja Heritage Suite' },
          ],
        },
        {
          key: 'baseRateMinor',
          label: 'Base Tariff per Night',
          type: 'currency',
          required: true,
          showInList: true,
          order: 3,
          width: 'half',
        },
        {
          key: 'maxOccupancy',
          label: 'Max Guests (Adults + Kids)',
          type: 'number',
          required: true,
          showInList: true,
          order: 4,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Housekeeping Status',
          type: 'select',
          required: true,
          showInList: true,
          order: 5,
          width: 'half',
          options: [
            { value: 'clean', label: 'Clean & Ready' },
            { value: 'occupied', label: 'Occupied' },
            { value: 'dirty', label: 'Dirty / Needs Cleaning' },
            { value: 'cleaning', label: 'Cleaning in Progress' },
            { value: 'maintenance', label: 'Under Maintenance' },
          ],
        },
        {
          key: 'floor',
          label: 'Floor / Wing',
          type: 'select',
          required: false,
          showInList: true,
          order: 6,
          width: 'half',
          options: [
            { value: 'ground', label: 'Ground Floor Garden' },
            { value: 'first', label: 'First Courtyard Floor' },
            { value: 'rooftop', label: 'Rooftop Pavilion' },
          ],
        },
        {
          key: 'amenities',
          label: 'Room Amenities',
          type: 'text',
          required: false,
          showInList: false,
          order: 7,
          width: 'full',
        },
      ],
    },

    // 2. Reservations — Date-Range Stay bookings
    {
      key: 'reservations',
      singular: 'Reservation',
      plural: 'Reservations',
      icon: 'Calendar',
      system: true,
      permissionKey: 'records.reservations',
      emptyStateText: 'No reservations logged. Book rooms for incoming guests.',
      listColumns: ['reservationCode', 'guestName', 'roomNumber', 'checkInDate', 'checkOutDate', 'status'],
      defaultSort: { field: 'checkInDate', dir: 'desc' },
      searchableFields: ['reservationCode', 'guestName', 'guestPhone', 'roomNumber'],
      fields: [
        {
          key: 'reservationCode',
          label: 'Reservation Code',
          type: 'autoId',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'guestName',
          label: 'Guest Full Name',
          type: 'text',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
        },
        {
          key: 'guestPhone',
          label: 'Guest Phone (WhatsApp)',
          type: 'phone',
          required: true,
          showInList: true,
          order: 3,
          width: 'half',
        },
        {
          key: 'roomNumber',
          label: 'Assigned Room',
          type: 'text',
          required: true,
          showInList: true,
          order: 4,
          width: 'half',
        },
        {
          key: 'checkInDate',
          label: 'Check-In Date',
          type: 'date',
          required: true,
          showInList: true,
          order: 5,
          width: 'half',
        },
        {
          key: 'checkOutDate',
          label: 'Check-Out Date',
          type: 'date',
          required: true,
          showInList: true,
          order: 6,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Reservation Status',
          type: 'select',
          required: true,
          showInList: true,
          order: 7,
          width: 'half',
          options: [
            { value: 'confirmed', label: 'Confirmed Booking' },
            { value: 'checked_in', label: 'Checked In (In-House)' },
            { value: 'checked_out', label: 'Checked Out' },
            { value: 'cancelled', label: 'Cancelled' },
            { value: 'no_show', label: 'No Show' },
          ],
        },
        {
          key: 'ratePerNightMinor',
          label: 'Agreed Rate / Night',
          type: 'currency',
          required: true,
          showInList: false,
          order: 8,
          width: 'half',
        },
        {
          key: 'advancePaidMinor',
          label: 'Advance Deposit Paid',
          type: 'currency',
          required: false,
          showInList: true,
          order: 9,
          width: 'half',
        },
        {
          key: 'numberOfGuests',
          label: 'Number of Guests',
          type: 'number',
          required: false,
          showInList: false,
          order: 10,
          width: 'half',
        },
        {
          key: 'specialRequests',
          label: 'Special Requests & Flight Info',
          type: 'textarea',
          required: false,
          showInList: false,
          order: 11,
          width: 'full',
        },
      ],
    },

    // 3. Guests — Indian Hospitality KYC & ID Proof compliance
    {
      key: 'guests',
      singular: 'Guest',
      plural: 'Guests',
      icon: 'Users',
      system: true,
      permissionKey: 'records.guests',
      emptyStateText: 'No guests registered. KYC and contact profiles are stored here.',
      listColumns: ['fullName', 'phone', 'city', 'idProofType', 'idProofNumber'],
      defaultSort: { field: 'fullName', dir: 'asc' },
      searchableFields: ['fullName', 'phone', 'email', 'idProofNumber', 'city'],
      fields: [
        {
          key: 'fullName',
          label: 'Guest Full Name',
          type: 'text',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Mobile Number',
          type: 'phone',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
        },
        {
          key: 'email',
          label: 'Email Address',
          type: 'email',
          required: false,
          showInList: true,
          order: 3,
          width: 'half',
        },
        {
          key: 'city',
          label: 'City / Origin Country',
          type: 'text',
          required: false,
          showInList: true,
          order: 4,
          width: 'half',
        },
        {
          key: 'idProofType',
          label: 'Govt. ID Proof Type',
          type: 'select',
          required: true,
          showInList: true,
          order: 5,
          width: 'half',
          options: [
            { value: 'aadhaar', label: 'Aadhaar Card' },
            { value: 'passport', label: 'Passport (International / Domestic)' },
            { value: 'driving_license', label: 'Driving License' },
            { value: 'voter_id', label: 'Voter ID' },
          ],
        },
        {
          key: 'idProofNumber',
          label: 'ID Proof Document Number',
          type: 'text',
          required: true,
          sensitive: true, // Invariant 7: Protected KYC
          showInList: true,
          order: 6,
          width: 'half',
        },
        {
          key: 'gstin',
          label: 'Company GSTIN (If Business Trip)',
          type: 'text',
          required: false,
          showInList: false,
          order: 7,
          width: 'half',
        },
        {
          key: 'notes',
          label: 'Preferences & Dietary Habits',
          type: 'textarea',
          required: false,
          showInList: false,
          order: 8,
          width: 'full',
        },
      ],
    },

    // 4. Folios ("Guest Bills") — Live running bill during stay
    {
      key: 'folios',
      singular: 'Guest Bill',
      plural: 'Guest Bills',
      icon: 'Receipt',
      system: true,
      permissionKey: 'records.folios',
      emptyStateText: 'No open guest bills. Running folios are created automatically per reservation.',
      listColumns: ['billNumber', 'guestName', 'roomNumber', 'roomChargesMinor', 'serviceChargesMinor', 'totalDueMinor', 'status'],
      defaultSort: { field: 'billNumber', dir: 'desc' },
      searchableFields: ['billNumber', 'guestName', 'roomNumber'],
      fields: [
        {
          key: 'billNumber',
          label: 'Bill Number',
          type: 'autoId',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'guestName',
          label: 'Guest Name',
          type: 'text',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
        },
        {
          key: 'roomNumber',
          label: 'Room Number',
          type: 'text',
          required: true,
          showInList: true,
          order: 3,
          width: 'half',
        },
        {
          key: 'roomChargesMinor',
          label: 'Room Tariff Subtotal',
          type: 'currency',
          required: true,
          showInList: true,
          order: 4,
          width: 'half',
        },
        {
          key: 'serviceChargesMinor',
          label: 'Dining & Services Subtotal',
          type: 'currency',
          required: false,
          showInList: true,
          order: 5,
          width: 'half',
        },
        {
          key: 'advanceDeductedMinor',
          label: 'Advance Deposit Deducted',
          type: 'currency',
          required: false,
          showInList: false,
          order: 6,
          width: 'half',
        },
        {
          key: 'taxAmountMinor',
          label: 'GST Tax (12%)',
          type: 'currency',
          required: true,
          showInList: false,
          order: 7,
          width: 'half',
        },
        {
          key: 'totalDueMinor',
          label: 'Net Balance Due',
          type: 'currency',
          required: true,
          showInList: true,
          order: 8,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Bill Status',
          type: 'select',
          required: true,
          showInList: true,
          order: 9,
          width: 'half',
          options: [
            { value: 'open', label: 'Open (Active Stay)' },
            { value: 'settled', label: 'Settled & Paid' },
          ],
        },
      ],
    },

    // 5. Room Service Orders
    {
      key: 'room_service',
      singular: 'Room Service Order',
      plural: 'Room Service Orders',
      icon: 'Utensils',
      system: false,
      permissionKey: 'records.room_service',
      emptyStateText: 'No dining orders placed yet.',
      listColumns: ['orderNumber', 'roomNumber', 'itemsSummary', 'amountMinor', 'status'],
      defaultSort: { field: 'orderNumber', dir: 'desc' },
      searchableFields: ['orderNumber', 'roomNumber', 'itemsSummary'],
      fields: [
        {
          key: 'orderNumber',
          label: 'Order ID',
          type: 'autoId',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'roomNumber',
          label: 'Room Number',
          type: 'text',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
        },
        {
          key: 'itemsSummary',
          label: 'Dishes & Drinks Ordered',
          type: 'textarea',
          required: true,
          showInList: true,
          order: 3,
          width: 'full',
        },
        {
          key: 'amountMinor',
          label: 'Order Amount',
          type: 'currency',
          required: true,
          showInList: true,
          order: 4,
          width: 'half',
        },
        {
          key: 'postedToFolio',
          label: 'Posted to Guest Bill',
          type: 'checkbox',
          required: false,
          showInList: true,
          order: 5,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Order Status',
          type: 'select',
          required: true,
          showInList: true,
          order: 6,
          width: 'half',
          options: [
            { value: 'preparing', label: 'Kitchen Preparing' },
            { value: 'delivered', label: 'Delivered to Room' },
            { value: 'billed', label: 'Billed to Room' },
          ],
        },
      ],
    },

    // 6. Seasonal Rate Rules
    {
      key: 'rate_rules',
      singular: 'Seasonal Rate Rule',
      plural: 'Rate Rules',
      icon: 'Tag',
      system: false,
      permissionKey: 'records.rate_rules',
      emptyStateText: 'No seasonal rate rules configured.',
      listColumns: ['seasonName', 'roomType', 'multiplierPercent', 'dateRange'],
      defaultSort: { field: 'seasonName', dir: 'asc' },
      searchableFields: ['seasonName', 'roomType'],
      fields: [
        {
          key: 'seasonName',
          label: 'Season Name',
          type: 'text',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'dateRange',
          label: 'Applicable Dates',
          type: 'text',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
        },
        {
          key: 'multiplierPercent',
          label: 'Rate Adjustment (+/- %)',
          type: 'number',
          required: true,
          showInList: true,
          order: 3,
          width: 'half',
        },
        {
          key: 'roomType',
          label: 'Applicable Room Type',
          type: 'select',
          required: true,
          showInList: true,
          order: 4,
          width: 'half',
          options: [
            { value: 'all', label: 'All Room Types' },
            { value: 'standard', label: 'Standard Heritage' },
            { value: 'deluxe', label: 'Deluxe Courtyard' },
            { value: 'suite', label: 'Royal Suite' },
          ],
        },
      ],
    },

    // 7. Invoices — Settled GST Invoices
    {
      key: 'invoices',
      singular: 'Tax Invoice',
      plural: 'Tax Invoices',
      icon: 'FileText',
      system: true,
      permissionKey: 'records.invoices',
      emptyStateText: 'No settled invoices generated yet.',
      listColumns: ['invoiceNumber', 'guestName', 'roomNumber', 'nights', 'netPaidMinor', 'paymentMode'],
      defaultSort: { field: 'invoiceNumber', dir: 'desc' },
      searchableFields: ['invoiceNumber', 'guestName', 'roomNumber'],
      fields: [
        {
          key: 'invoiceNumber',
          label: 'Invoice Number',
          type: 'autoId',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'guestName',
          label: 'Guest Name',
          type: 'text',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
        },
        {
          key: 'roomNumber',
          label: 'Room Number',
          type: 'text',
          required: true,
          showInList: true,
          order: 3,
          width: 'half',
        },
        {
          key: 'nights',
          label: 'Nights Stayed',
          type: 'number',
          required: true,
          showInList: true,
          order: 4,
          width: 'half',
        },
        {
          key: 'subtotalMinor',
          label: 'Taxable Subtotal',
          type: 'currency',
          required: true,
          showInList: false,
          order: 5,
          width: 'half',
        },
        {
          key: 'cgstMinor',
          label: 'CGST (6%)',
          type: 'currency',
          required: true,
          showInList: false,
          order: 6,
          width: 'half',
        },
        {
          key: 'sgstMinor',
          label: 'SGST (6%)',
          type: 'currency',
          required: true,
          showInList: false,
          order: 7,
          width: 'half',
        },
        {
          key: 'advanceAdjustedMinor',
          label: 'Advance Adjusted',
          type: 'currency',
          required: false,
          showInList: false,
          order: 8,
          width: 'half',
        },
        {
          key: 'netPaidMinor',
          label: 'Total Settled Amount',
          type: 'currency',
          required: true,
          showInList: true,
          order: 9,
          width: 'half',
        },
        {
          key: 'paymentMode',
          label: 'Payment Method',
          type: 'select',
          required: true,
          showInList: true,
          order: 10,
          width: 'half',
          options: [
            { value: 'upi', label: 'UPI / QR Payment' },
            { value: 'card', label: 'Credit / Debit Card' },
            { value: 'cash', label: 'Cash' },
            { value: 'bank_transfer', label: 'Direct Bank Transfer' },
          ],
        },
      ],
    },

    // 8. Staff
    {
      key: 'staff',
      singular: 'Staff Member',
      plural: 'Staff',
      icon: 'UserCheck',
      system: false,
      permissionKey: 'records.staff',
      emptyStateText: 'No staff profiles added.',
      listColumns: ['fullName', 'role', 'shift', 'phone'],
      defaultSort: { field: 'fullName', dir: 'asc' },
      searchableFields: ['fullName', 'role', 'phone'],
      fields: [
        {
          key: 'fullName',
          label: 'Staff Full Name',
          type: 'text',
          required: true,
          showInList: true,
          order: 1,
          width: 'half',
        },
        {
          key: 'role',
          label: 'Designation / Department',
          type: 'select',
          required: true,
          showInList: true,
          order: 2,
          width: 'half',
          options: [
            { value: 'manager', label: 'General Manager' },
            { value: 'front_desk', label: 'Front Desk Executive' },
            { value: 'housekeeping', label: 'Housekeeping Lead' },
            { value: 'chef', label: 'Head Chef' },
            { value: 'security', label: 'Security & Concierge' },
          ],
        },
        {
          key: 'shift',
          label: 'Assigned Shift',
          type: 'select',
          required: true,
          showInList: true,
          order: 3,
          width: 'half',
          options: [
            { value: 'morning', label: 'Morning Shift (7 AM - 3 PM)' },
            { value: 'evening', label: 'Evening Shift (3 PM - 11 PM)' },
            { value: 'night', label: 'Night Shift (11 PM - 7 AM)' },
          ],
        },
        {
          key: 'phone',
          label: 'Mobile Number',
          type: 'phone',
          required: true,
          showInList: true,
          order: 4,
          width: 'half',
        },
      ],
    },

    // 9. Expenses (Universal Core for P&L)
    ...universalCoreEntities.filter((e) => e.key === 'expenses' || e.key === 'tasks'),
  ],
  workflows: [
    {
      id: 'wf-housekeeping',
      title: 'Rooms Housekeeping Status',
      entityKey: 'rooms',
      stageField: 'status',
      stages: [
        { key: 'clean', label: 'Clean & Ready', color: 'emerald' },
        { key: 'occupied', label: 'Occupied', color: 'indigo' },
        { key: 'dirty', label: 'Needs Cleaning', color: 'amber' },
        { key: 'cleaning', label: 'In Progress', color: 'sky' },
        { key: 'maintenance', label: 'Maintenance', color: 'rose' },
      ],
    },
    {
      id: 'wf-reservations',
      title: 'Stay Reservations Pipeline',
      entityKey: 'reservations',
      stageField: 'status',
      stages: [
        { key: 'confirmed', label: 'Confirmed', color: 'sky' },
        { key: 'checked_in', label: 'In-House (Checked-In)', color: 'indigo' },
        { key: 'checked_out', label: 'Checked-Out', color: 'emerald' },
        { key: 'cancelled', label: 'Cancelled', color: 'slate' },
      ],
    },
  ],
  automations: [
    {
      id: 'auto-res-whatsapp',
      name: 'Reservation Confirmation & Directions (WhatsApp)',
      trigger: 'record_created',
      entityKey: 'reservations',
      action: 'send_whatsapp',
      template: 'Namaste {{guestName}}, your booking at {{tenantName}} is confirmed for Room {{roomNumber}} from {{checkInDate}} to {{checkOutDate}}. Amber Fort road directions: goo.gl/amber-haveli',
      enabled: true,
    },
    {
      id: 'auto-room-clean-alert',
      name: 'Room Ready for Check-in Alert',
      trigger: 'stage_changed',
      entityKey: 'rooms',
      action: 'send_notification',
      template: 'Room {{roomNumber}} has been cleaned and inspected. Ready for guest check-in.',
      enabled: true,
    },
    {
      id: 'auto-checkout-reminder',
      name: 'Checkout & Express Bill Settlement Reminder',
      trigger: 'scheduled_time',
      entityKey: 'reservations',
      action: 'send_whatsapp',
      template: 'Namaste {{guestName}}, we hope you enjoyed your heritage stay. Standard checkout is at 11:00 AM. Your guest bill is ready at front desk or on UPI.',
      enabled: true,
    },
  ],
  dashboard: {
    widgets: [
      {
        id: 'w-rooms-total',
        type: 'stat_card',
        title: 'Available Rooms',
        dataSource: { entity: 'rooms' },
      },
      {
        id: 'w-active-reservations',
        type: 'stat_card',
        title: 'In-House Guests',
        dataSource: { entity: 'reservations' },
      },
      {
        id: 'w-guest-bills',
        type: 'stat_card',
        title: 'Open Guest Bills',
        dataSource: { entity: 'folios' },
      },
      {
        id: 'w-dining-orders',
        type: 'stat_card',
        title: 'Room Service Today',
        dataSource: { entity: 'room_service' },
      },
    ],
  },
  website: {
    published: true,
    subdomain: 'heritage-haveli-jaipur',
    theme: {
      primaryColor: '#b45309',
      accentColor: '#d97706',
      backgroundColor: '#fdfbf7',
      fontFamily: 'serif',
    },
    seo: {
      metaTitle: 'The Grand Heritage Haveli & Guesthouse | Amber Fort, Jaipur',
      metaDescription: 'Authentic 18th-century Rajputana haveli guesthouse with courtyards, rooftop views of Amber Fort, Rajasthani royal dining, and boutique rooms.',
    },
    sections: [
      {
        id: 'sec-hero',
        type: 'hero',
        title: 'An Authentic Royal Haven in the Heart of Jaipur',
        subtitle: 'Experience centuries of Rajputana hospitality, hand-painted frescoes, serene courtyards, and rooftop views of the majestic Amber Fort.',
        ctaText: 'Reserve Your Room',
        ctaLink: '#booking',
        visible: true,
      },
      {
        id: 'sec-rooms',
        type: 'services',
        title: 'Heritage Chambers & Suites',
        subtitle: 'Each room is individually curated with antique teak furnishings, carved stone arches, and modern luxury conveniences.',
        visible: true,
      },
      {
        id: 'sec-booking',
        type: 'booking',
        title: 'Direct Reservation & Best Tariff Guarantee',
        subtitle: 'Select your arrival date and preferred heritage suite. Instant WhatsApp booking confirmation.',
        visible: true,
      },
      {
        id: 'sec-contact',
        type: 'contact',
        title: 'Location & Concierge',
        subtitle: 'Heritage Palace Road, Amber Fort Enclave, Jaipur. 20 minutes from Jaipur International Airport.',
        visible: true,
      },
    ],
  },
};
