/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Stage 14: Comprehensive Restaurant / Café Template (India Business Essentials)
 * Spice & Savor Café, Indiranagar, Bengaluru
 */

import { TenantConfig } from '../../types/config.ts';

export const restaurantTemplate: TenantConfig = {
  id: 'template-restaurant',
  slug: 'spice-savor-cafe',
  name: 'Spice & Savor Café',
  businessTypeKey: 'restaurant',
  status: 'active',
  schemaVersion: 1,
  profile: {
    phone: '+91 99112 23344',
    email: 'dine@spiceandsavor.in',
    address: '42, 12th Main, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560008',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    currency: 'INR',
    taxRate: 5, // Restaurant GST is 5% in India
    gstin: '29AABCS8899R1Z1',
    stateCode: '29',
    stateName: 'Karnataka',
  },
  branding: {
    primary: '#ea580c', // Orange warm
    secondary: '#1c1917',
    accent: '#f97316',
    font: 'sans-serif',
    radius: 'lg',
    buttonStyle: 'solid',
    mode: 'light',
    loginHeadline: 'Spice & Savor Café — Table & Kitchen POS',
  },
  modules: {
    orders: { enabled: true },
    menu: { enabled: true },
    tables: { enabled: true },
    reservations: { enabled: true },
    billing: { enabled: true },
  },
  roleLabels: {
    business_admin: 'Café General Manager',
    staff: 'Captain / Head Waiter',
  },
  entities: [
    // 1. Menu Items (7 fields)
    {
      key: 'menu_items',
      singular: 'Menu Dish',
      plural: 'Menu Items',
      icon: 'Utensils',
      system: true,
      permissionKey: 'records.menu',
      emptyStateText: 'No dishes added to the menu yet.',
      searchableFields: ['name', 'category'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['name', 'category', 'dietType', 'priceMinor', 'isAvailable'],
      fields: [
        {
          key: 'name',
          label: 'Dish Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'category',
          label: 'Menu Section',
          type: 'select',
          options: [
            { value: 'breakfast', label: 'Artisan Breakfast & Sourdough' },
            { value: 'coffee', label: 'Specialty Pour-over & Espresso' },
            { value: 'mains', label: 'Main Courses & Bowls' },
            { value: 'desserts', label: 'Pastries & Desserts' },
          ],
          defaultValue: 'coffee',
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'dietType',
          label: 'Dietary Mark',
          type: 'select',
          options: [
            { value: 'veg', label: 'Vegetarian (Green Dot)' },
            { value: 'non_veg', label: 'Non-Vegetarian (Red Dot)' },
            { value: 'vegan', label: 'Vegan (Pure Plant)' },
          ],
          defaultValue: 'veg',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'priceMinor',
          label: 'Price',
          type: 'currency',
          defaultValue: 38000, // ₹380
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'isAvailable',
          label: 'Available to Order',
          type: 'checkbox',
          defaultValue: true,
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '996331',
          hsnOrSac: '996331',
          order: 6,
          showInList: false,
          width: 'half',
          helpText: 'Tax code: 996331 (Restaurant dining services, 5% GST)',
        },
        {
          key: 'description',
          label: 'Ingredients & Preparation',
          type: 'text',
          order: 7,
          showInList: false,
          width: 'full',
        },
      ],
    },

    // 2. Categories (2 fields)
    {
      key: 'categories',
      singular: 'Menu Category',
      plural: 'Menu Categories',
      icon: 'Tag',
      system: true,
      permissionKey: 'records.categories',
      emptyStateText: 'No menu categories created.',
      searchableFields: ['name'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['name', 'displayOrder'],
      fields: [
        {
          key: 'name',
          label: 'Section Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'displayOrder',
          label: 'Display Order',
          type: 'number',
          defaultValue: 1,
          order: 2,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 3. Orders (Kitchen Workflow, 6 fields)
    {
      key: 'orders',
      singular: 'Kitchen Order (KOT)',
      plural: 'Orders',
      icon: 'FileText',
      system: true,
      permissionKey: 'records.orders',
      emptyStateText: 'No live kitchen orders.',
      searchableFields: ['orderNumber', 'tableNumber', 'customerName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['orderNumber', 'orderType', 'tableNumber', 'status', 'totalAmountMinor', 'paymentStatus'],
      fields: [
        {
          key: 'orderNumber',
          label: 'Order ID / KOT',
          type: 'autoId',
          autoIdPattern: 'KOT-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'orderType',
          label: 'Service Type',
          type: 'select',
          options: [
            { value: 'dine_in', label: 'Dine-In Table' },
            { value: 'takeaway', label: 'Takeaway Counter' },
            { value: 'delivery', label: 'Doorstep Delivery' },
          ],
          defaultValue: 'dine_in',
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'tableNumber',
          label: 'Assigned Table',
          type: 'text',
          defaultValue: 'Table T-04',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'itemsSummary',
          label: 'Dishes Ordered',
          type: 'text',
          defaultValue: '2x Truffle Pasta, 1x Iced Americano, 1x Tiramisu',
          order: 4,
          showInList: false,
          width: 'full',
        },
        {
          key: 'status',
          label: 'Kitchen Order Status',
          type: 'select',
          options: [
            { value: 'placed', label: 'Order Placed (KOT Printed)', color: 'blue' },
            { value: 'preparing', label: 'Cooking in Kitchen', color: 'amber' },
            { value: 'ready', label: 'Food Ready for Pickup', color: 'purple' },
            { value: 'served', label: 'Served to Table / Delivered', color: 'green' },
          ],
          defaultValue: 'placed',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'totalAmountMinor',
          label: 'Order Total (Incl. 5% GST)',
          type: 'currency',
          defaultValue: 114450, // ₹1,144.50
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentStatus',
          label: 'Settlement Status',
          type: 'select',
          options: [
            { value: 'pending', label: 'Running Bill', color: 'amber' },
            { value: 'paid', label: 'Paid & Settled', color: 'green' },
          ],
          defaultValue: 'pending',
          order: 7,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 4. Tables (Table Workflow, 3 fields)
    {
      key: 'tables',
      singular: 'Dining Table',
      plural: 'Tables',
      icon: 'Grid',
      system: true,
      permissionKey: 'records.tables',
      emptyStateText: 'No restaurant tables configured.',
      searchableFields: ['tableNumber'],
      defaultSort: { field: 'tableNumber', dir: 'asc' },
      listColumns: ['tableNumber', 'capacity', 'status'],
      fields: [
        {
          key: 'tableNumber',
          label: 'Table Number',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'capacity',
          label: 'How many people can join this class?', // Plain language reuse for capacity
          type: 'number',
          defaultValue: 4,
          order: 2,
          showInList: true,
          width: 'half',
          helpText: 'Seating capacity for table arrangement',
        },
        {
          key: 'status',
          label: 'Floor Status',
          type: 'select',
          options: [
            { value: 'free', label: 'Available / Free', color: 'green' },
            { value: 'occupied', label: 'Occupied / Dining', color: 'rose' },
            { value: 'billed', label: 'Bill Presented', color: 'amber' },
            { value: 'cleaning', label: 'Sanitizing & Resetting', color: 'slate' },
          ],
          defaultValue: 'free',
          order: 3,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 5. Reservations (7 fields)
    {
      key: 'reservations',
      singular: 'Table Booking',
      plural: 'Reservations',
      icon: 'Calendar',
      system: true,
      permissionKey: 'records.reservations',
      emptyStateText: 'No table bookings for today.',
      searchableFields: ['customerName', 'phone'],
      defaultSort: { field: 'reservationTime', dir: 'asc' },
      listColumns: ['customerName', 'phone', 'partySize', 'reservationDate', 'reservationTime', 'tableAssigned'],
      fields: [
        {
          key: 'customerName',
          label: 'Guest Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Phone Number',
          type: 'phone',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'partySize',
          label: 'Party Size (Guests)',
          type: 'number',
          defaultValue: 4,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'reservationDate',
          label: 'Date',
          type: 'date',
          required: true,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'reservationTime',
          label: 'Time Slot',
          type: 'text',
          defaultValue: '08:00 PM',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'tableAssigned',
          label: 'Table Reserved',
          type: 'text',
          defaultValue: 'Table T-06 (Balcony)',
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'notes',
          label: 'Special Occasion / Dietary Notes',
          type: 'text',
          order: 7,
          showInList: false,
          width: 'full',
          helpText: 'e.g. Anniversary celebration, requests quiet corner',
        },
      ],
    },

    // 6. Staff (4 fields)
    {
      key: 'staff',
      singular: 'Team Member',
      plural: 'Restaurant Staff',
      icon: 'Users',
      system: true,
      permissionKey: 'records.staff',
      emptyStateText: 'No café team members added.',
      searchableFields: ['name', 'role'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['staffId', 'name', 'role', 'shift', 'phone'],
      fields: [
        {
          key: 'staffId',
          label: 'Employee ID',
          type: 'autoId',
          autoIdPattern: 'EMP-{SEQ:2}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'name',
          label: 'Staff Member Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'role',
          label: 'Café Role',
          type: 'text',
          defaultValue: 'Head Barista',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'shift',
          label: 'Shift Timing',
          type: 'text',
          defaultValue: 'Morning Shift (07:00 AM - 03:30 PM)',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Phone Number',
          type: 'phone',
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 7. Invoices (GST Compliant, Split Bill, Tip, 8 fields)
    {
      key: 'invoices',
      singular: 'Dining Bill',
      plural: 'Restaurant Bills',
      icon: 'Receipt',
      system: true,
      permissionKey: 'records.invoices',
      emptyStateText: 'No bills generated today.',
      searchableFields: ['invoiceId', 'tableNumber'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['invoiceId', 'tableNumber', 'subtotalMinor', 'grandTotalMinor', 'paymentStatus', 'paymentMethod'],
      fields: [
        {
          key: 'invoiceId',
          label: 'Bill Number',
          type: 'autoId',
          autoIdPattern: 'CAFE-2026-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'tableNumber',
          label: 'Table Number',
          type: 'text',
          defaultValue: 'Table T-04',
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'subtotalMinor',
          label: 'Food & Beverage Subtotal',
          type: 'currency',
          defaultValue: 185000, // ₹1,850
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '996331',
          hsnOrSac: '996331',
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'tipMinor',
          label: 'Staff Gratuity / Tip',
          type: 'currency',
          defaultValue: 10000, // ₹100
          order: 5,
          showInList: false,
          width: 'half',
        },
        {
          key: 'grandTotalMinor',
          label: 'Grand Total (Incl. 5% GST)',
          type: 'currency',
          defaultValue: 204250, // ₹2,042.50
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentStatus',
          label: 'Bill Status',
          type: 'select',
          options: [
            { value: 'paid', label: 'Settled / Paid', color: 'green' },
            { value: 'pending', label: 'Pending Payment', color: 'amber' },
          ],
          defaultValue: 'paid',
          order: 7,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentMethod',
          label: 'Settlement Mode',
          type: 'select',
          options: [
            { value: 'upi', label: 'UPI / Dynamic QR' },
            { value: 'card', label: 'Credit / Debit Card' },
            { value: 'cash', label: 'Cash' },
          ],
          defaultValue: 'upi',
          order: 8,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 8. Ingredient Stock (Batch & Expiry Tracked, 6 fields)
    {
      key: 'ingredient_stock',
      singular: 'Kitchen Ingredient',
      plural: 'Ingredient Pantry',
      icon: 'Coffee',
      system: true,
      batchTracked: true,
      permissionKey: 'records.ingredients',
      emptyStateText: 'No pantry inventory recorded.',
      searchableFields: ['name', 'batchNumber'],
      defaultSort: { field: 'expiryDate', dir: 'asc' },
      listColumns: ['name', 'batchNumber', 'expiryDate', 'quantity', 'unit', 'reorderLevel'],
      fields: [
        {
          key: 'name',
          label: 'Pantry Item / Dairy',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'batchNumber',
          label: 'Batch / Lot Number',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'expiryDate',
          label: 'Expiry Date',
          type: 'date',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
          helpText: 'Perishable freshness date for food safety compliance',
        },
        {
          key: 'quantity',
          label: 'Available Quantity',
          type: 'number',
          defaultValue: 25,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'unit',
          label: 'Unit of Measure',
          type: 'select',
          options: [
            { value: 'kg', label: 'Kilograms (kg)' },
            { value: 'liters', label: 'Liters (L)' },
            { value: 'packets', label: 'Packets' },
          ],
          defaultValue: 'kg',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'reorderLevel',
          label: 'Restock Warning Threshold',
          type: 'number',
          defaultValue: 8,
          order: 6,
          showInList: true,
          width: 'half',
        },
      ],
    },
  ],

  // 2 Workflow Boards
  workflows: [
    {
      id: 'restaurant_orders_workflow',
      title: 'Kitchen Order Pipeline (KOT)',
      entityKey: 'orders',
      statusFieldKey: 'status',
      stages: [
        { key: 'placed', label: 'KOT Placed', color: 'bg-blue-50 border-blue-200 text-blue-800' },
        { key: 'preparing', label: 'Cooking in Kitchen', color: 'bg-amber-50 border-amber-200 text-amber-800' },
        { key: 'ready', label: 'Ready for Pickup', color: 'bg-purple-50 border-purple-200 text-purple-800' },
        { key: 'served', label: 'Served to Table', color: 'bg-emerald-50 border-emerald-200 text-emerald-800' },
      ],
      cardDisplayFields: ['orderNumber', 'tableNumber', 'orderType', 'totalAmountMinor'],
    },
    {
      id: 'restaurant_tables_workflow',
      title: 'Table Turnover Board',
      entityKey: 'tables',
      statusFieldKey: 'status',
      stages: [
        { key: 'free', label: 'Free Table', color: 'bg-emerald-50 border-emerald-200 text-emerald-800' },
        { key: 'occupied', label: 'Occupied', color: 'bg-rose-50 border-rose-200 text-rose-800' },
        { key: 'billed', label: 'Billed', color: 'bg-amber-50 border-amber-200 text-amber-800' },
        { key: 'cleaning', label: 'Cleaning & Reset', color: 'bg-slate-50 border-slate-200 text-slate-700' },
      ],
      cardDisplayFields: ['tableNumber', 'capacity'],
    },
  ],

  // 3 Automations
  automations: [
    {
      id: 'auto_rest_reservation_reminder',
      name: 'Table Reservation Reminder (3h Before)',
      description: 'Sends WhatsApp booking confirmation and location pin to reserved guests.',
      trigger: 'scheduled_daily',
      entityKey: 'reservations',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'appointment_reminder',
      },
      enabled: true,
    },
    {
      id: 'auto_rest_low_ingredient',
      name: 'Pantry Low-Ingredient Alert',
      description: 'Alerts head chef via SMS when organic milk or coffee bean stock reaches restock point.',
      trigger: 'low_stock',
      entityKey: 'ingredient_stock',
      condition: { field: 'quantity', operator: 'lte', value: 8 },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'low_stock_alert',
      },
      enabled: true,
    },
    {
      id: 'auto_rest_order_ready',
      name: 'Takeaway Order Ready Notification',
      description: 'Dispatches WhatsApp message to takeaway customer when kitchen finishes packing.',
      trigger: 'status_change',
      entityKey: 'orders',
      condition: { field: 'status', operator: 'eq', value: 'ready' },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'order_ready',
      },
      enabled: true,
    },
  ],

  // 4 Dashboard Widgets
  dashboard: {
    widgets: [
      {
        id: 'widget-today-orders',
        type: 'metric',
        title: "Today's Table Orders",
        span: 1,
        order: 1,
        dataSource: { entity: 'orders', aggregate: 'count', range: 'today' },
      },
      {
        id: 'widget-revenue-30d',
        type: 'metric',
        title: 'Café Receipts (30d)',
        span: 1,
        order: 2,
        dataSource: { entity: 'invoices', aggregate: 'sum', field: 'grandTotalMinor', range: '30d' },
      },
      {
        id: 'widget-table-occupancy',
        type: 'metric',
        title: 'Occupied Tables',
        span: 1,
        order: 3,
        dataSource: { entity: 'tables', aggregate: 'count', filter: { field: 'status', operator: 'eq', value: 'occupied' } },
      },
      {
        id: 'widget-popular-items',
        type: 'metric',
        title: 'Active Menu Offerings',
        span: 1,
        order: 4,
        dataSource: { entity: 'menu_items', aggregate: 'count', filter: { field: 'isAvailable', operator: 'eq', value: true } },
      },
    ],
  },

  // 3 Reports
  reports: [
    {
      id: 'rep_rest_sales_period',
      title: 'Daily & Weekly Café Sales',
      description: 'Dine-in vs Takeaway receipts, average order value, and 5% GST breakup.',
      category: 'sales',
      entityKey: 'invoices',
      metricKey: 'grandTotalMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_rest_item_popularity',
      title: 'Menu Dish Popularity & Contribution',
      description: 'Sales volume across specialty coffees, breakfast sourdoughs, and bowls.',
      category: 'sales',
      entityKey: 'menu_items',
      metricKey: 'priceMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_rest_peak_hours',
      title: 'Peak Service Hour & Turnover Analysis',
      description: 'Table turnover rates and peak lunch/dinner rush times.',
      category: 'operations',
      entityKey: 'orders',
      metricKey: 'orderNumber',
      timeframeDefault: '30d',
    },
  ],

  website: {
    draft: {
      headline: 'Specialty Sourdough & Single-Origin Roasts',
      tagline: 'Artisan café and roastery in Indiranagar, Bengaluru. Craft coffee, brunch, and mindful slow dining.',
      themeName: 'warm-bistro',
      sections: [
        {
          id: 'sec-hero',
          type: 'hero',
          title: 'Craft Coffee & Elevated Brunch in Indiranagar',
          subtitle: 'Single-estate Chikmagalur pour-overs, naturally fermented sourdough tartines, and hand-spun gelato.',
          enabled: true,
          content: { ctaText: 'Reserve Table for Brunch', ctaLink: '#booking' },
        },
        {
          id: 'sec-services',
          type: 'services',
          title: 'Specialty Roastery & Bakery',
          enabled: true,
          content: {
            items: [
              { name: 'Single-Origin Pour-Overs', desc: 'Light and medium roasts sourced directly from shaded Western Ghats estates.' },
              { name: 'Naturally Fermented Sourdough', desc: 'Baked fresh every morning with organic whole grain flour and 36-hour wild yeast.' },
              { name: 'Fresh Farm-to-Table Bowls', desc: 'Heirloom greens, cold-pressed dressings, and seasonal roasted grains.' },
            ],
          },
        },
      ],
    },
    published: null,
  },
  subscription: {
    plan: 'professional',
    status: 'active',
    startedAt: '2026-01-01T00:00:00Z',
    renewsAt: '2027-01-01T00:00:00Z',
    limits: { users: 10, records: 50000, storageMb: 5000, modules: ['orders', 'menu', 'tables', 'reservations', 'billing'] },
    usage: { users: 2, records: 45, storageMb: 11 },
  },
};
