/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Stage 14: Comprehensive Retail Template (India Business Essentials)
 * Craft & Clay Goods, Indiranagar, Bengaluru
 */

import { TenantConfig } from '../../types/config.ts';

export const retailTemplate: TenantConfig = {
  id: 'template-retail',
  slug: 'craft-corner-store',
  name: 'Craft & Clay Goods Store',
  businessTypeKey: 'retail',
  status: 'active',
  schemaVersion: 1,
  profile: {
    phone: '+91 99887 66554',
    email: 'hello@craftandclay.in',
    address: 'Shop 12, 100 Feet Road, Indiranagar, Bengaluru, Karnataka 560038',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    currency: 'INR',
    taxRate: 18,
    gstin: '29AABCC5432E1Z2',
    stateCode: '29',
    stateName: 'Karnataka',
  },
  branding: {
    primary: '#d97706', // Amber warm
    secondary: '#1c1917',
    accent: '#f59e0b',
    font: 'sans-serif',
    radius: 'lg',
    buttonStyle: 'solid',
    mode: 'light',
    loginHeadline: 'Craft & Clay Goods — Artisan Retail POS',
  },
  modules: {
    inventory: { enabled: true },
    orders: { enabled: true },
    customers: { enabled: true },
    billing: { enabled: true },
    loyalty: { enabled: true },
  },
  roleLabels: {
    business_admin: 'Store Manager',
    staff: 'Sales Assistant',
  },
  entities: [
    // 1. Products (12 fields with barcode, batch toggle, and HSN)
    {
      key: 'products',
      singular: 'Product',
      plural: 'Products',
      icon: 'ShoppingBag',
      system: true,
      permissionKey: 'records.products',
      emptyStateText: 'No products added yet. Add your first item to build your inventory catalog.',
      searchableFields: ['name', 'sku', 'barcode', 'category'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['sku', 'name', 'barcode', 'category', 'sellingPriceMinor', 'stockQuantity'],
      fields: [
        {
          key: 'sku',
          label: 'Product Code (SKU)',
          type: 'autoId',
          autoIdPattern: 'SKU-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'name',
          label: 'Product Title',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'barcode',
          label: 'Barcode / QR Code',
          type: 'barcode',
          order: 3,
          showInList: true,
          width: 'half',
          helpText: 'Scan with camera or generate printable sticker',
        },
        {
          key: 'category',
          label: 'Category',
          type: 'select',
          options: [
            { value: 'ceramics', label: 'Artisan Ceramics & Tableware' },
            { value: 'pottery', label: 'Handmade Planters & Vases' },
            { value: 'woodcraft', label: 'Teak & Rosewood Kitchenware' },
            { value: 'fragrance', label: 'Scented Soy Candles' },
            { value: 'linen', label: 'Pure Cotton Table Runners' },
          ],
          defaultValue: 'ceramics',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'brand',
          label: 'Artisan / Maker Brand',
          type: 'text',
          defaultValue: 'Craft & Clay In-House Studio',
          order: 5,
          showInList: false,
          width: 'half',
        },
        {
          key: 'batchTracked',
          label: 'Track by batch & expiry — good for medicines, cosmetics, and food',
          type: 'checkbox',
          defaultValue: false,
          order: 6,
          showInList: false,
          width: 'full',
          helpText: 'Enable if this item has batch numbers or expiry dates',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '691110',
          hsnOrSac: '691110',
          taxRate: 18,
          order: 7,
          showInList: false,
          width: 'half',
          helpText: 'Tax code: 691110 (Ceramic tableware & kitchenware, 18% GST)',
        },
        {
          key: 'purchasePriceMinor',
          label: 'Purchase Cost',
          type: 'currency',
          defaultValue: 45000, // ₹450
          order: 8,
          showInList: false,
          width: 'half',
        },
        {
          key: 'sellingPriceMinor',
          label: 'Retail Price (MRP)',
          type: 'currency',
          defaultValue: 89000, // ₹890
          order: 9,
          showInList: true,
          width: 'half',
        },
        {
          key: 'taxRate',
          label: 'GST Rate (%)',
          type: 'number',
          defaultValue: 18,
          order: 10,
          showInList: false,
          width: 'half',
        },
        {
          key: 'reorderLevel',
          label: 'Low Stock Reorder Alert',
          type: 'number',
          defaultValue: 10,
          order: 11,
          showInList: false,
          width: 'half',
        },
        {
          key: 'stockQuantity',
          label: 'Available In Stock',
          type: 'number',
          defaultValue: 45,
          order: 12,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 2. Categories (2 fields)
    {
      key: 'categories',
      singular: 'Product Category',
      plural: 'Product Categories',
      icon: 'Tag',
      system: true,
      permissionKey: 'records.categories',
      emptyStateText: 'No product categories configured.',
      searchableFields: ['name'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['name', 'parentCategory'],
      fields: [
        {
          key: 'name',
          label: 'Category Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'parentCategory',
          label: 'Parent Category',
          type: 'text',
          defaultValue: 'Home & Living',
          order: 2,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 3. Suppliers (6 fields)
    {
      key: 'suppliers',
      singular: 'Artisan Supplier',
      plural: 'Suppliers',
      icon: 'Truck',
      system: true,
      permissionKey: 'records.suppliers',
      emptyStateText: 'No artisan suppliers registered yet.',
      searchableFields: ['name', 'phone'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['supplierId', 'name', 'phone', 'email', 'itemsSupplied'],
      fields: [
        {
          key: 'supplierId',
          label: 'Supplier Code',
          type: 'autoId',
          autoIdPattern: 'SUP-{SEQ:3}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'name',
          label: 'Supplier / Workshop Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Phone Number',
          type: 'phone',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'email',
          label: 'Email Address',
          type: 'email',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'address',
          label: 'Studio Workshop Address',
          type: 'text',
          order: 5,
          showInList: false,
          width: 'full',
        },
        {
          key: 'itemsSupplied',
          label: 'Craft Supplies',
          type: 'text',
          defaultValue: 'Stoneware ceramics, terracotta mugs, glazed pots',
          order: 6,
          showInList: true,
          width: 'full',
        },
      ],
    },

    // 4. Customers (7 fields with Loyalty Points)
    {
      key: 'customers',
      singular: 'Customer',
      plural: 'Customers',
      icon: 'Users',
      system: true,
      permissionKey: 'records.customers',
      emptyStateText: 'No registered customers yet.',
      searchableFields: ['fullName', 'phone', 'email'],
      defaultSort: { field: 'fullName', dir: 'asc' },
      listColumns: ['customerId', 'fullName', 'phone', 'loyaltyPoints', 'city'],
      fields: [
        {
          key: 'customerId',
          label: 'Customer ID',
          type: 'autoId',
          autoIdPattern: 'CUST-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'fullName',
          label: 'Customer Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Mobile Number',
          type: 'phone',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'email',
          label: 'Email Address',
          type: 'email',
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'city',
          label: 'City / Locality',
          type: 'text',
          defaultValue: 'Bengaluru',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'loyaltyPoints',
          label: 'Loyalty Points Balance',
          type: 'number',
          defaultValue: 150,
          order: 6,
          showInList: true,
          width: 'half',
          helpText: 'Redeemable at counter: 1 point = ₹1 discount',
        },
        {
          key: 'notes',
          label: 'Preferences & Gifting Notes',
          type: 'text',
          order: 7,
          showInList: false,
          width: 'full',
        },
      ],
    },

    // 5. Purchases (Purchase Orders with Workflow)
    {
      key: 'purchases',
      singular: 'Purchase Order',
      plural: 'Purchase Orders',
      icon: 'ClipboardList',
      system: true,
      permissionKey: 'records.purchases',
      emptyStateText: 'No purchase orders generated.',
      searchableFields: ['orderNumber', 'supplierName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['orderNumber', 'supplierName', 'orderDate', 'totalAmountMinor', 'status'],
      fields: [
        {
          key: 'orderNumber',
          label: 'PO Number',
          type: 'autoId',
          autoIdPattern: 'PO-2026-{SEQ:3}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'supplierName',
          label: 'Artisan Supplier',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'orderDate',
          label: 'PO Issue Date',
          type: 'date',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'status',
          label: 'PO Status',
          type: 'select',
          options: [
            { value: 'ordered', label: 'Ordered with Artisan', color: 'blue' },
            { value: 'received', label: 'Received & Quality Checked', color: 'amber' },
            { value: 'stocked', label: 'Stocked on Shelves', color: 'green' },
          ],
          defaultValue: 'ordered',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'totalAmountMinor',
          label: 'Total PO Value',
          type: 'currency',
          defaultValue: 3500000, // ₹35,000
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'itemsSummary',
          label: 'Line Items Summary',
          type: 'text',
          defaultValue: '50x Glazed Ceramic Mugs, 20x Teak Wood Salad Bowls',
          order: 6,
          showInList: false,
          width: 'full',
        },
      ],
    },

    // 6. Sales / Invoices (GST Compliant, Line Items, Loyalty, 11 fields)
    {
      key: 'sales_invoices',
      singular: 'Retail Sale Bill',
      plural: 'Sales & Invoices',
      icon: 'Receipt',
      system: true,
      permissionKey: 'records.sales',
      emptyStateText: 'No retail sales logged today.',
      searchableFields: ['invoiceNumber', 'customerName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['invoiceNumber', 'customerName', 'subtotalMinor', 'grandTotalMinor', 'paymentStatus', 'paymentMethod'],
      fields: [
        {
          key: 'invoiceNumber',
          label: 'Bill Number',
          type: 'autoId',
          autoIdPattern: 'RET-2026-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'customerName',
          label: 'Customer Name',
          type: 'text',
          defaultValue: 'Walk-in Shopper',
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'customerGstin',
          label: 'Customer GSTIN (For B2B)',
          type: 'text',
          order: 3,
          showInList: false,
          width: 'half',
          helpText: 'Optional 15-digit GSTIN for business input tax credit',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '691110',
          hsnOrSac: '691110',
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'isInterState',
          label: 'Inter-State Sale (100% IGST)',
          type: 'checkbox',
          defaultValue: false,
          order: 5,
          showInList: false,
          width: 'half',
          helpText: 'Unchecked = Karnataka (CGST 9% + SGST 9%)',
        },
        {
          key: 'subtotalMinor',
          label: 'Item Subtotal',
          type: 'currency',
          defaultValue: 240000, // ₹2,400
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'discountMinor',
          label: 'Discount / Promo',
          type: 'currency',
          defaultValue: 0,
          order: 7,
          showInList: false,
          width: 'half',
        },
        {
          key: 'loyaltyPointsRedeemed',
          label: 'Loyalty Points Used',
          type: 'number',
          defaultValue: 0,
          order: 8,
          showInList: false,
          width: 'half',
        },
        {
          key: 'grandTotalMinor',
          label: 'Final Bill Amount (Incl. GST)',
          type: 'currency',
          defaultValue: 283200, // ₹2,832 (incl 18% GST)
          order: 9,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentStatus',
          label: 'Payment Status',
          type: 'select',
          options: [
            { value: 'paid', label: 'Paid in Full', color: 'green' },
            { value: 'pending', label: 'Awaiting Payment', color: 'amber' },
            { value: 'overdue', label: 'Overdue B2B Credit', color: 'rose' },
          ],
          defaultValue: 'paid',
          order: 10,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentMethod',
          label: 'Tender Mode',
          type: 'select',
          options: [
            { value: 'upi', label: 'UPI / QR Code' },
            { value: 'card', label: 'Credit / Debit Card' },
            { value: 'cash', label: 'Cash at Counter' },
          ],
          defaultValue: 'upi',
          order: 11,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 7. Stock Movements (Ledger, 6 fields)
    {
      key: 'stock_movements',
      singular: 'Stock Movement',
      plural: 'Stock Movements',
      icon: 'ArrowLeftRight',
      system: true,
      permissionKey: 'records.movements',
      emptyStateText: 'No stock adjustments logged.',
      searchableFields: ['productName', 'reference'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['movementId', 'productName', 'movementType', 'quantity', 'reference'],
      fields: [
        {
          key: 'movementId',
          label: 'Movement Entry ID',
          type: 'autoId',
          autoIdPattern: 'MOV-{SEQ:5}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'productName',
          label: 'Product Title',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'movementType',
          label: 'Movement Reason',
          type: 'select',
          options: [
            { value: 'stock_in', label: 'Inward / Restock' },
            { value: 'sale', label: 'Outward / POS Sale' },
            { value: 'return', label: 'Customer Return' },
            { value: 'damage', label: 'Damaged / Broken in Transit' },
          ],
          defaultValue: 'sale',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'quantity',
          label: 'Units Changed',
          type: 'number',
          defaultValue: -2,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'reference',
          label: 'Bill or PO Reference',
          type: 'text',
          defaultValue: 'RET-2026-0012',
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'notes',
          label: 'Audit Remarks',
          type: 'text',
          order: 6,
          showInList: false,
          width: 'full',
        },
      ],
    },

    // 8. Stock Batches (Batch & Expiry Tracked for cosmetics & candles, 5 fields)
    {
      key: 'stock_batches',
      singular: 'Stock Batch',
      plural: 'Stock Batches',
      icon: 'Boxes',
      system: true,
      batchTracked: true,
      permissionKey: 'records.batches',
      emptyStateText: 'No batch-tracked lots recorded.',
      searchableFields: ['batchNumber', 'productName'],
      defaultSort: { field: 'expiryDate', dir: 'asc' },
      listColumns: ['batchNumber', 'productName', 'expiryDate', 'quantity', 'purchaseRateMinor'],
      fields: [
        {
          key: 'batchNumber',
          label: 'Batch Number',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
          helpText: 'e.g. BATCH-CC-2026-04',
        },
        {
          key: 'productName',
          label: 'Product Item',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'expiryDate',
          label: 'Expiry Date',
          type: 'date',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'quantity',
          label: 'Quantity in Batch',
          type: 'number',
          defaultValue: 30,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'purchaseRateMinor',
          label: 'Unit Cost Rate',
          type: 'currency',
          defaultValue: 45000,
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },
  ],

  // 1 Workflow Board: Purchase Orders
  workflows: [
    {
      id: 'retail_purchase_workflow',
      title: 'Purchase Order Pipeline',
      entityKey: 'purchases',
      statusFieldKey: 'status',
      stages: [
        { key: 'ordered', label: 'Ordered', color: 'bg-blue-50 border-blue-200 text-blue-800' },
        { key: 'received', label: 'Received & Inspected', color: 'bg-amber-50 border-amber-200 text-amber-800' },
        { key: 'stocked', label: 'Shelved & In Stock', color: 'bg-emerald-50 border-emerald-200 text-emerald-800' },
      ],
      cardDisplayFields: ['orderNumber', 'supplierName', 'totalAmountMinor'],
    },
  ],

  // 4 Automation Presets
  automations: [
    {
      id: 'auto_retail_low_stock',
      name: 'Inventory Low-Stock Warning',
      description: 'Sends SMS notification to store manager when SKU count breaches safety threshold.',
      trigger: 'low_stock',
      entityKey: 'products',
      condition: { field: 'stockQuantity', operator: 'lte', value: 10 },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'low_stock_alert',
      },
      enabled: true,
    },
    {
      id: 'auto_retail_expiry_alert',
      name: 'Perishable Batch Expiry Alert',
      description: 'Alerts staff 30 days before scented candles and organic balms expire.',
      trigger: 'expiry_approaching',
      entityKey: 'stock_batches',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'expiry_approaching',
      },
      enabled: true,
    },
    {
      id: 'auto_retail_payment_overdue',
      name: 'Invoice Payment Due Reminder',
      description: 'Sends automated WhatsApp notification to B2B credit accounts with pending balances.',
      trigger: 'status_change',
      entityKey: 'sales_invoices',
      condition: { field: 'paymentStatus', operator: 'eq', value: 'overdue' },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'invoice_due',
      },
      enabled: true,
    },
    {
      id: 'auto_retail_order_ready',
      name: 'Customer Order Ready Dispatch',
      description: 'Notifies customers via WhatsApp when bespoke pottery gift orders are ready for pickup.',
      trigger: 'status_change',
      entityKey: 'sales_invoices',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'order_ready',
      },
      enabled: true,
    },
  ],

  // 6 Dashboard Widgets
  dashboard: {
    widgets: [
      {
        id: 'widget-total-products',
        type: 'metric',
        title: 'Catalog Items (SKUs)',
        span: 1,
        order: 1,
        dataSource: { entity: 'products', aggregate: 'count' },
      },
      {
        id: 'widget-inventory-value',
        type: 'metric',
        title: 'Holding Stock Valuation',
        span: 1,
        order: 2,
        dataSource: { entity: 'products', aggregate: 'sum', field: 'sellingPriceMinor' },
      },
      {
        id: 'widget-low-stock-count',
        type: 'metric',
        title: 'Low-Stock Alerts',
        span: 1,
        order: 3,
        dataSource: { entity: 'products', aggregate: 'count', filter: { field: 'stockQuantity', operator: 'lte', value: 10 } },
      },
      {
        id: 'widget-today-sales',
        type: 'metric',
        title: "Today's POS Billings",
        span: 1,
        order: 4,
        dataSource: { entity: 'sales_invoices', aggregate: 'sum', field: 'grandTotalMinor', range: 'today' },
      },
      {
        id: 'widget-monthly-revenue',
        type: 'metric',
        title: 'Monthly Store Revenue',
        span: 1,
        order: 5,
        dataSource: { entity: 'sales_invoices', aggregate: 'sum', field: 'grandTotalMinor', range: '30d' },
      },
      {
        id: 'widget-pending-payments',
        type: 'metric',
        title: 'Unpaid Receivables',
        span: 1,
        order: 6,
        dataSource: { entity: 'sales_invoices', aggregate: 'count', filter: { field: 'paymentStatus', operator: 'neq', value: 'paid' } },
      },
    ],
  },

  // 5 Reports
  reports: [
    {
      id: 'rep_retail_sales_period',
      title: 'Sales & Invoices by Period',
      description: 'Daily, weekly, and monthly retail revenue trends.',
      category: 'sales',
      entityKey: 'sales_invoices',
      metricKey: 'grandTotalMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_retail_gst_summary',
      title: 'GST Tax Summary (GSTR-1 Ready)',
      description: 'Taxable values, CGST, SGST, and IGST breakdowns across B2C and B2B sales.',
      category: 'tax',
      entityKey: 'sales_invoices',
      metricKey: 'grandTotalMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_retail_stock_valuation',
      title: 'Current Stock Valuation & Margins',
      description: 'Total holding inventory cost vs retail value.',
      category: 'inventory',
      entityKey: 'products',
      metricKey: 'stockQuantity',
      timeframeDefault: 'today',
    },
    {
      id: 'rep_retail_profit_estimate',
      title: 'Estimated Gross Profit Analysis',
      description: 'Retail revenue minus cost of goods sold (COGS).',
      category: 'sales',
      entityKey: 'sales_invoices',
      metricKey: 'subtotalMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_retail_top_sellers',
      title: 'Top-Selling Artisan Products',
      description: 'Best performing SKUs ranked by transaction frequency.',
      category: 'sales',
      entityKey: 'products',
      metricKey: 'sellingPriceMinor',
      timeframeDefault: '30d',
    },
  ],

  website: {
    draft: {
      headline: 'Handcrafted Ceramic & Artisanal Living',
      tagline: 'Artisan tableware, terracotta pottery, and curated home goods in Indiranagar, Bengaluru.',
      themeName: 'warm-artisan',
      sections: [
        {
          id: 'sec-hero',
          type: 'hero',
          title: 'Crafted for Mindful Daily Rituals',
          subtitle: 'Each bowl, mug, and vase is shaped and high-fired by master Indian artisans with non-toxic glazes.',
          enabled: true,
          content: { ctaText: 'Visit Our Indiranagar Store', ctaLink: '#contact' },
        },
        {
          id: 'sec-services',
          type: 'services',
          title: 'Curated Artisan Collections',
          enabled: true,
          content: {
            items: [
              { name: 'Stoneware Tableware', desc: 'Microwave and dishwasher safe artisan dining ceramics.' },
              { name: 'Terracotta Planters', desc: 'Breathable, naturally porous pots for lush indoor plants.' },
              { name: 'Soy Wax Scented Candles', desc: 'Hand-poured aromatic botanicals in reusable stoneware jars.' },
            ],
          },
        },
      ],
    },
    published: null,
  },
  subscription: {
    plan: 'professional',
    status: 'active',
    startedAt: '2026-01-01T00:00:00Z',
    renewsAt: '2027-01-01T00:00:00Z',
    limits: { users: 10, records: 50000, storageMb: 5000, modules: ['inventory', 'orders', 'customers', 'billing'] },
    usage: { users: 2, records: 64, storageMb: 15 },
  },
};
