/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Stage 14: Comprehensive Salon / Spa Template (India Business Essentials)
 * Priya's Salon Studio, Bandra West, Mumbai
 */

import { TenantConfig } from '../../types/config.ts';

export const salonTemplate: TenantConfig = {
  id: 'template-salon',
  slug: 'priya-salon-studio',
  name: "Priya's Salon Studio",
  businessTypeKey: 'salon',
  status: 'active',
  schemaVersion: 1,
  profile: {
    phone: '+91 98123 45678',
    email: 'hello@priyasalon.in',
    address: '14 Blossom Lane, Off Turner Road, Bandra West, Mumbai, Maharashtra 400050',
    timezone: 'Asia/Kolkata',
    locale: 'en-IN',
    currency: 'INR',
    taxRate: 18,
    gstin: '27AABCP9876K1Z4',
    stateCode: '27',
    stateName: 'Maharashtra',
  },
  branding: {
    primary: '#db2777', // Pink-600
    secondary: '#831843',
    accent: '#f472b6',
    font: 'sans-serif',
    radius: 'lg',
    buttonStyle: 'solid',
    mode: 'light',
    loginHeadline: "Priya's Salon Studio — Beauty & Wellness Management",
  },
  modules: {
    bookings: { enabled: true },
    services: { enabled: true },
    clients: { enabled: true },
    billing: { enabled: true },
    loyalty: { enabled: true },
    packages: { enabled: true },
  },
  roleLabels: {
    business_admin: 'Salon Creative Director',
    staff: 'Senior Hair & Beauty Stylist',
  },
  entities: [
    // 1. Clients (7 fields)
    {
      key: 'clients',
      singular: 'Client',
      plural: 'Clients',
      icon: 'Sparkles',
      system: true,
      permissionKey: 'records.clients',
      emptyStateText: 'No clients saved yet. Add your regular clients to start booking appointments.',
      searchableFields: ['fullName', 'phone', 'email'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['clientId', 'fullName', 'phone', 'loyaltyPoints', 'preferredStylist'],
      fields: [
        {
          key: 'clientId',
          label: 'Client ID',
          type: 'autoId',
          autoIdPattern: 'CLI-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'fullName',
          label: 'Client Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Mobile Phone',
          type: 'phone',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'email',
          label: 'Email Address',
          type: 'email',
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'loyaltyPoints',
          label: 'Loyalty Points Balance',
          type: 'number',
          defaultValue: 120,
          order: 5,
          showInList: true,
          width: 'half',
          helpText: 'Earn 1 point per ₹100 spent. Redeemable on salon services.',
        },
        {
          key: 'preferredStylist',
          label: 'Preferred Stylist',
          type: 'text',
          defaultValue: 'Priya Sharma',
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'beautyNotes',
          label: 'Hair / Skin Preferences & Allergies',
          type: 'textarea',
          sensitive: true,
          order: 7,
          showInList: false,
          width: 'full',
          helpText: 'Sensitive scalp, allergy to ammonia dyes, favorite beverage',
        },
      ],
    },

    // 2. Services (4 fields)
    {
      key: 'services',
      singular: 'Salon Service',
      plural: 'Salon Services',
      icon: 'Scissors',
      system: true,
      permissionKey: 'records.services',
      emptyStateText: 'No salon services listed.',
      searchableFields: ['title', 'category'],
      defaultSort: { field: 'title', dir: 'asc' },
      listColumns: ['serviceId', 'title', 'category', 'priceMinor', 'durationMinutes'],
      fields: [
        {
          key: 'serviceId',
          label: 'Service Code',
          type: 'autoId',
          autoIdPattern: 'SRV-{SEQ:3}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'title',
          label: 'Service Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'category',
          label: 'Service Category',
          type: 'select',
          options: [
            { value: 'hair', label: 'Hair Cut, Color & Styling' },
            { value: 'facial', label: 'Skin Care & Organic Facials' },
            { value: 'nails', label: 'Manicure & Pedicure' },
            { value: 'spa', label: 'Body Spa & Aromatherapy' },
            { value: 'bridal', label: 'Bridal & Party Makeovers' },
          ],
          defaultValue: 'hair',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'priceMinor',
          label: 'Standard Price',
          type: 'currency',
          defaultValue: 150000, // ₹1,500
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'durationMinutes',
          label: 'Duration (Minutes)',
          type: 'number',
          defaultValue: 45,
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 3. Products (Barcode & Batch Tracked, 7 fields)
    {
      key: 'products',
      singular: 'Beauty Product',
      plural: 'Retail Products',
      icon: 'Package',
      system: true,
      permissionKey: 'records.products',
      emptyStateText: 'No retail products listed.',
      searchableFields: ['name', 'brand', 'barcode'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['name', 'brand', 'barcode', 'sellingPriceMinor', 'stock'],
      fields: [
        {
          key: 'name',
          label: 'Product Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'brand',
          label: 'Cosmetics Brand',
          type: 'text',
          defaultValue: "L'Oreal Professional",
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'barcode',
          label: 'Barcode / QR',
          type: 'barcode',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'category',
          label: 'Product Type',
          type: 'select',
          options: [
            { value: 'shampoo', label: 'Hair Care & Serums' },
            { value: 'skincare', label: 'Face Creams & Scrubs' },
            { value: 'color', label: 'Hair Colors & Developers' },
          ],
          defaultValue: 'shampoo',
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'sellingPriceMinor',
          label: 'Retail Price (MRP)',
          type: 'currency',
          defaultValue: 180000, // ₹1,800
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'stock',
          label: 'Units on Shelf',
          type: 'number',
          defaultValue: 18,
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'batchTracked',
          label: 'Track by batch & expiry — good for medicines, cosmetics, and food',
          type: 'checkbox',
          defaultValue: true,
          order: 7,
          showInList: false,
          width: 'full',
        },
      ],
    },

    // 4. Appointments (8 fields with Stylist, Status, Walk-in flag)
    {
      key: 'appointments',
      singular: 'Salon Appointment',
      plural: 'Appointments',
      icon: 'Calendar',
      system: true,
      permissionKey: 'records.appointments',
      emptyStateText: 'No appointments scheduled for today.',
      searchableFields: ['clientName', 'stylistName'],
      defaultSort: { field: 'appointmentDate', dir: 'asc' },
      listColumns: ['appointmentId', 'clientName', 'stylistName', 'serviceName', 'appointmentTime', 'status'],
      fields: [
        {
          key: 'appointmentId',
          label: 'Booking Code',
          type: 'autoId',
          autoIdPattern: 'BK-{YYYY}-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'clientName',
          label: 'Client Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'stylistName',
          label: 'Assigned Stylist',
          type: 'text',
          defaultValue: 'Priya Sharma',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'serviceName',
          label: 'Booked Service',
          type: 'text',
          defaultValue: 'Hair Cut & Styling',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'appointmentDate',
          label: 'Date',
          type: 'date',
          required: true,
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'appointmentTime',
          label: 'Time Slot',
          type: 'text',
          defaultValue: '03:00 PM',
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Service Status',
          type: 'select',
          options: [
            { value: 'booked', label: 'Booked', color: 'blue' },
            { value: 'checked_in', label: 'Checked In / Waiting', color: 'amber' },
            { value: 'in_service', label: 'In Service / Chair', color: 'purple' },
            { value: 'completed', label: 'Completed', color: 'green' },
            { value: 'no_show', label: 'No-Show', color: 'slate' },
          ],
          defaultValue: 'booked',
          order: 7,
          showInList: true,
          width: 'half',
        },
        {
          key: 'isWalkIn',
          label: 'Walk-in Client without Prior Booking',
          type: 'checkbox',
          defaultValue: false,
          order: 8,
          showInList: false,
          width: 'half',
        },
      ],
    },

    // 5. Staff / Stylists (5 fields with Commission Rate)
    {
      key: 'staff_stylists',
      singular: 'Stylist & Therapist',
      plural: 'Stylists & Staff',
      icon: 'User',
      system: true,
      permissionKey: 'records.staff',
      emptyStateText: 'No stylists recorded.',
      searchableFields: ['name', 'specialties'],
      defaultSort: { field: 'name', dir: 'asc' },
      listColumns: ['stylistId', 'name', 'specialties', 'commissionPercent', 'phone'],
      fields: [
        {
          key: 'stylistId',
          label: 'Stylist ID',
          type: 'autoId',
          autoIdPattern: 'STY-{SEQ:2}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'name',
          label: 'Stylist Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'commissionPercent',
          label: 'Commission Rate (%)',
          type: 'number',
          defaultValue: 15,
          order: 3,
          showInList: true,
          width: 'half',
          helpText: 'Percentage paid to stylist on completed services',
        },
        {
          key: 'specialties',
          label: 'Specialty Skills',
          type: 'text',
          defaultValue: 'Balayage, Keratin, Bridal Makeup',
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'phone',
          label: 'Phone Number',
          type: 'phone',
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 6. Memberships / Packages (Recurring / Prepaid, 7 fields)
    {
      key: 'memberships',
      singular: 'Membership / Package',
      plural: 'Memberships & Packages',
      icon: 'Award',
      system: true,
      permissionKey: 'records.memberships',
      emptyStateText: 'No client memberships issued.',
      searchableFields: ['packageName', 'clientName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['packageName', 'clientName', 'sessionsIncluded', 'sessionsRemaining', 'priceMinor', 'status'],
      fields: [
        {
          key: 'packageName',
          label: 'Membership / Package',
          type: 'text',
          defaultValue: 'Glow & Shine Spa Pass',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'clientName',
          label: 'Client Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'sessionsIncluded',
          label: 'Total Sessions',
          type: 'number',
          defaultValue: 6,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'sessionsRemaining',
          label: 'Sessions Left',
          type: 'number',
          defaultValue: 4,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'validityDays',
          label: 'Validity (Days)',
          type: 'number',
          defaultValue: 90,
          order: 5,
          showInList: false,
          width: 'half',
        },
        {
          key: 'priceMinor',
          label: 'Package Price',
          type: 'currency',
          defaultValue: 699900, // ₹6,999
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'status',
          label: 'Plan Status',
          type: 'select',
          options: [
            { value: 'active', label: 'Active', color: 'green' },
            { value: 'expired', label: 'Expired', color: 'rose' },
            { value: 'renewed', label: 'Renewed', color: 'blue' },
          ],
          defaultValue: 'active',
          order: 7,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 7. Invoices (7 fields with Service + Product lines, GST, Stylist Commission)
    {
      key: 'invoices',
      singular: 'Salon Invoice',
      plural: 'Salon Invoices',
      icon: 'Receipt',
      system: true,
      permissionKey: 'records.invoices',
      emptyStateText: 'No invoices created.',
      searchableFields: ['invoiceId', 'clientName'],
      defaultSort: { field: 'createdAt', dir: 'desc' },
      listColumns: ['invoiceId', 'clientName', 'stylistName', 'grandTotalMinor', 'paymentStatus', 'paymentMethod'],
      fields: [
        {
          key: 'invoiceId',
          label: 'Invoice Number',
          type: 'autoId',
          autoIdPattern: 'SAL-2026-{SEQ:4}',
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'clientName',
          label: 'Client Name',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'stylistName',
          label: 'Stylist Attended',
          type: 'text',
          defaultValue: 'Priya Sharma',
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'taxCode',
          label: 'Tax code (for GST)',
          type: 'text',
          defaultValue: '999721',
          hsnOrSac: '999721',
          order: 4,
          showInList: false,
          width: 'half',
        },
        {
          key: 'grandTotalMinor',
          label: 'Total Bill (Incl. 18% GST)',
          type: 'currency',
          defaultValue: 236000, // ₹2,360
          order: 5,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentStatus',
          label: 'Payment Status',
          type: 'select',
          options: [
            { value: 'paid', label: 'Paid in Full', color: 'green' },
            { value: 'pending', label: 'Pending', color: 'amber' },
          ],
          defaultValue: 'paid',
          order: 6,
          showInList: true,
          width: 'half',
        },
        {
          key: 'paymentMethod',
          label: 'Tender Mode',
          type: 'select',
          options: [
            { value: 'upi', label: 'UPI / QR Code' },
            { value: 'card', label: 'Credit / Debit Card' },
            { value: 'cash', label: 'Cash' },
          ],
          defaultValue: 'upi',
          order: 7,
          showInList: true,
          width: 'half',
        },
      ],
    },

    // 8. Salon Stock (Batch & Expiry Tracked cosmetics & dyes, 5 fields)
    {
      key: 'salon_stock',
      singular: 'Salon Stock Item',
      plural: 'Beauty Stock & Dyes',
      icon: 'SprayCan',
      system: true,
      batchTracked: true,
      permissionKey: 'records.stock',
      emptyStateText: 'No beauty stock recorded.',
      searchableFields: ['productName', 'batchNumber'],
      defaultSort: { field: 'expiryDate', dir: 'asc' },
      listColumns: ['productName', 'batchNumber', 'expiryDate', 'quantity', 'unit'],
      fields: [
        {
          key: 'productName',
          label: 'Product / Cosmetic Name',
          type: 'text',
          required: true,
          order: 1,
          showInList: true,
          width: 'half',
        },
        {
          key: 'batchNumber',
          label: 'Batch Number',
          type: 'text',
          required: true,
          order: 2,
          showInList: true,
          width: 'half',
        },
        {
          key: 'expiryDate',
          label: 'Expiry Date',
          type: 'date',
          required: true,
          order: 3,
          showInList: true,
          width: 'half',
        },
        {
          key: 'quantity',
          label: 'Quantity in Salon',
          type: 'number',
          defaultValue: 15,
          order: 4,
          showInList: true,
          width: 'half',
        },
        {
          key: 'unit',
          label: 'Packaging Unit',
          type: 'select',
          options: [
            { value: 'tube', label: 'Color Tubes (60ml)' },
            { value: 'bottle_1l', label: 'Salon Shampoos (1L)' },
            { value: 'jar', label: 'Face Massage Cream Jars' },
          ],
          defaultValue: 'tube',
          order: 5,
          showInList: true,
          width: 'half',
        },
      ],
    },
  ],

  // 1 Workflow Board
  workflows: [
    {
      id: 'salon_appointments_workflow',
      title: 'Salon Floor Workflow Board',
      entityKey: 'appointments',
      statusFieldKey: 'status',
      stages: [
        { key: 'booked', label: 'Booked', color: 'bg-blue-50 border-blue-200 text-blue-800' },
        { key: 'checked_in', label: 'Checked In / Waiting', color: 'bg-amber-50 border-amber-200 text-amber-800' },
        { key: 'in_service', label: 'In Service / Chair', color: 'bg-purple-50 border-purple-200 text-purple-800' },
        { key: 'completed', label: 'Completed & Billed', color: 'bg-emerald-50 border-emerald-200 text-emerald-800' },
        { key: 'no_show', label: 'No-Show', color: 'bg-slate-50 border-slate-200 text-slate-700' },
      ],
      cardDisplayFields: ['clientName', 'stylistName', 'serviceName', 'appointmentTime'],
    },
  ],

  // 5 Automation Presets
  automations: [
    {
      id: 'auto_salon_reminder',
      name: 'Appointment Reminder (24h Before)',
      description: 'Sends WhatsApp appointment confirmation to client 24 hours in advance.',
      trigger: 'scheduled_daily',
      entityKey: 'appointments',
      condition: { field: 'status', operator: 'eq', value: 'booked' },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'appointment_reminder',
      },
      enabled: true,
    },
    {
      id: 'auto_salon_expiry_alert',
      name: 'Cosmetic & Dye Expiry Alert',
      description: 'Warns salon director 30 days before hair developer and facial packs expire.',
      trigger: 'expiry_approaching',
      entityKey: 'salon_stock',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'expiry_approaching',
      },
      enabled: true,
    },
    {
      id: 'auto_salon_low_stock',
      name: 'Salon Supply Low Stock Alert',
      description: 'Sends SMS to front desk when hair colors or shampoos drop below reorder quantity.',
      trigger: 'low_stock',
      entityKey: 'salon_stock',
      condition: { field: 'quantity', operator: 'lte', value: 5 },
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'low_stock_alert',
      },
      enabled: true,
    },
    {
      id: 'auto_salon_membership_expiring',
      name: 'Package Expiry Renewal Alert',
      description: 'Reminds clients 7 days before their prepaid salon package expires.',
      trigger: 'scheduled_daily',
      entityKey: 'memberships',
      action: {
        type: 'sendMessageTemplate',
        templateKey: 'membership_expiring',
      },
      enabled: true,
    },
    {
      id: 'auto_salon_loyalty_points',
      name: 'Loyalty Points on Bill Completion',
      description: 'Automatically awards 1 loyalty point per ₹100 billed on completed invoices.',
      trigger: 'status_change',
      entityKey: 'invoices',
      condition: { field: 'paymentStatus', operator: 'eq', value: 'paid' },
      action: {
        type: 'addLoyaltyPoints',
        pointsPerUnit: 1,
      },
      enabled: true,
    },
  ],

  // 5 Dashboard Widgets
  dashboard: {
    widgets: [
      {
        id: 'widget-today-appointments',
        type: 'metric',
        title: "Today's Appointments",
        span: 1,
        order: 1,
        dataSource: { entity: 'appointments', aggregate: 'count', range: 'today' },
      },
      {
        id: 'widget-revenue-30d',
        type: 'metric',
        title: 'Salon Revenue (30d)',
        span: 1,
        order: 2,
        dataSource: { entity: 'invoices', aggregate: 'sum', field: 'grandTotalMinor', range: '30d' },
      },
      {
        id: 'widget-top-stylist',
        type: 'metric',
        title: 'Lead Stylist',
        span: 1,
        order: 3,
        dataSource: { entity: 'appointments', aggregate: 'count' },
      },
      {
        id: 'widget-low-stock-count',
        type: 'metric',
        title: 'Low-Stock Cosmetics',
        span: 1,
        order: 4,
        dataSource: { entity: 'salon_stock', aggregate: 'count', filter: { field: 'quantity', operator: 'lte', value: 5 } },
      },
      {
        id: 'widget-active-memberships',
        type: 'metric',
        title: 'Active Spa Packages',
        span: 1,
        order: 5,
        dataSource: { entity: 'memberships', aggregate: 'count', filter: { field: 'status', operator: 'eq', value: 'active' } },
      },
    ],
  },

  // 4 Reports
  reports: [
    {
      id: 'rep_salon_staff_commissions',
      title: 'Stylist Commission & Performance Summary',
      description: 'Revenue generated and commission breakdown per stylist.',
      category: 'operations',
      entityKey: 'invoices',
      metricKey: 'grandTotalMinor',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_salon_service_popularity',
      title: 'Service Popularity & Utilization',
      description: 'Most popular treatments across hair, skin, and nails.',
      category: 'sales',
      entityKey: 'appointments',
      metricKey: 'serviceName',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_salon_client_retention',
      title: 'Client Retention & Rebooking Rate',
      description: 'Repeat visit rates and package utilization metrics.',
      category: 'operations',
      entityKey: 'clients',
      metricKey: 'loyaltyPoints',
      timeframeDefault: '30d',
    },
    {
      id: 'rep_salon_revenue_period',
      title: 'Salon Revenue & GST Collection',
      description: 'Service billings, retail cosmetics sales, and GST breakdown.',
      category: 'tax',
      entityKey: 'invoices',
      metricKey: 'grandTotalMinor',
      timeframeDefault: '30d',
    },
  ],

  website: {
    draft: {
      headline: 'Elevated Hair Artistry & Botanical Wellness',
      tagline: 'Premier boutique salon in Bandra West, Mumbai, curated by Creative Director Priya Sharma.',
      themeName: 'chic-luxury',
      sections: [
        {
          id: 'sec-hero',
          type: 'hero',
          title: 'Your Personal Haven of Beauty in Bandra',
          subtitle: 'Expert styling, customized balayage, and restorative organic facials with cruelty-free botanicals.',
          enabled: true,
          content: { ctaText: 'Book Stylist Appointment', ctaLink: '#booking' },
        },
        {
          id: 'sec-services',
          type: 'services',
          title: 'Signature Salon Treatments',
          enabled: true,
          content: {
            items: [
              { name: 'Custom Hair Styling & Color', desc: 'Personalized tones, gentle balayage, and deep hydration treatments.' },
              { name: 'Botanical Skin Therapy', desc: 'Revitalizing facials using pure, nutrient-rich organic botanicals.' },
              { name: 'Bridal & Red Carpet Artistry', desc: 'Impeccable makeup and timeless styling for unforgettable celebrations.' },
            ],
          },
        },
      ],
    },
    published: null,
  },
  subscription: {
    plan: 'professional',
    status: 'active',
    startedAt: '2026-01-01T00:00:00Z',
    renewsAt: '2027-01-01T00:00:00Z',
    limits: { users: 10, records: 50000, storageMb: 5000, modules: ['bookings', 'services', 'clients', 'billing'] },
    usage: { users: 2, records: 52, storageMb: 14 },
  },
};
