/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const websiteCopy = {
  tabTitle: 'Public Website',
  tabSubtitle: 'Manage your public-facing business website, preview live changes, and publish when ready.',
  badgeLive: 'Published & Live',
  badgeDraft: 'Draft Changes Pending',
  openSite: 'View Public Site',
  publishSite: 'Publish to Live Web',
  publishing: 'Publishing...',
  publishedSuccess: 'Your website changes are now live to your customers!',
  revertToPublished: 'Discard Draft Changes',
  sectionsTitle: 'Website Sections',
  sectionSubtitle: 'Turn sections on or off, edit your headline, and provide information for your customers.',
  headlineLabel: 'Main Headline',
  headlinePlaceholder: 'e.g., Compassionate Healthcare for Your Family',
  taglineLabel: 'Sub-Headline / Tagline',
  taglinePlaceholder: 'e.g., Book appointments easily and receive dedicated care.',
  themeLabel: 'Color Theme Style',
  sectionHero: 'Welcome Banner (Hero)',
  sectionHeroDesc: 'The first introduction visitors see when landing on your website.',
  sectionServices: 'Services & Pricing',
  sectionServicesDesc: 'List of services, treatments, or specialties offered.',
  sectionAbout: 'About Our Practice',
  sectionAboutDesc: 'Information about your experience, mission, and team.',
  sectionBooking: 'Online Booking Form',
  sectionBookingDesc: 'Allows customers to request or schedule appointments directly.',
  sectionContact: 'Contact & Location Info',
  sectionContactDesc: 'Shows phone number, email address, physical location, and business hours.',
  bookingModalTitle: 'Book an Appointment',
  bookingModalSubtitle: 'Select your preferred date, time, and tell us who is visiting.',
  bookingSuccessTitle: 'Appointment Request Received!',
  bookingSuccessDesc: 'Thank you! We have logged your appointment request and our team will get in touch shortly.',
  bookingError: 'Unable to submit booking request. Please check all fields and try again.',
  customerName: 'Full Name',
  customerPhone: 'Phone Number',
  customerEmail: 'Email Address (Optional)',
  serviceRequested: 'Service or Reason for Visit',
  appointmentDate: 'Preferred Date',
  appointmentTime: 'Preferred Time',
  additionalNotes: 'Additional Notes or Symptoms',
  submitBooking: 'Confirm Appointment Request',
  submittingBooking: 'Sending request...',
  publicSiteNotice: 'Public View — Accessible to any patient, client, or visitor without logging in.',
  backToAdmin: 'Return to Business Workspace',
} as const;
